# Copyright (C) 2002-2021 Free Software Foundation, Inc.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.
#
# As a special exception to the GNU General Public License,
# this file may be distributed as part of a program that
# contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.
#
# This file represents the specification of how gnulib-tool is used.
# It acts as a cache: It is written and read by gnulib-tool.
# In projects that use version control, this file is meant to be put under
# version control, like the configure.ac and various Makefile.am files.


# Specification in the form of a command-line invocation:
# gnulib-tool --import --local-dir=src/gl/override \
#  --lib=libgnu_gpl \
#  --source-base=src/gl \
#  --m4-base=src/gl/m4 \
#  --doc-base=doc \
#  --tests-base=src/gl/tests \
#  --aux-dir=build-aux \
#  --with-tests \
#  --no-conditional-dependencies \
#  --libtool \
#  --macro-prefix=ggl \
#  --no-vc-files \
#  accept \
#  alloca \
#  arpa_inet \
#  attribute \
#  bind \
#  byteswap \
#  c-ctype \
#  c-strcase \
#  close \
#  close-stream \
#  connect \
#  explicit_bzero \
#  fopen-gnu \
#  func \
#  getaddrinfo \
#  getline \
#  getpass \
#  gettext-h \
#  gettimeofday \
#  hash \
#  hash-pjw-bare \
#  inet_ntop \
#  inet_pton \
#  intprops \
#  inttypes \
#  linked-list \
#  listen \
#  lock \
#  memmem-simple \
#  minmax \
#  netdb \
#  netinet_in \
#  parse-datetime \
#  progname \
#  read-file \
#  reallocarray \
#  recv \
#  recvfrom \
#  secure_getenv \
#  select \
#  send \
#  sendto \
#  servent \
#  setsockopt \
#  shutdown \
#  snprintf \
#  socket \
#  sockets \
#  socklen \
#  stdint \
#  stpcpy \
#  strcase \
#  strdup-posix \
#  strndup \
#  strtok_r \
#  strverscmp \
#  sys_socket \
#  sys_stat \
#  sys_types \
#  threadlib \
#  time_r \
#  unistd \
#  valgrind-tests \
#  vasprintf \
#  verify \
#  vsnprintf \
#  xalloc \
#  xalloc-oversized \
#  xlist \
#  xsize

# Specification in the form of a few gnulib-tool.m4 macro invocations:
gl_LOCAL_DIR([src/gl/override])
gl_MODULES([
  accept
  alloca
  arpa_inet
  attribute
  bind
  byteswap
  c-ctype
  c-strcase
  close
  close-stream
  connect
  explicit_bzero
  fopen-gnu
  func
  getaddrinfo
  getline
  getpass
  gettext-h
  gettimeofday
  hash
  hash-pjw-bare
  inet_ntop
  inet_pton
  intprops
  inttypes
  linked-list
  listen
  lock
  memmem-simple
  minmax
  netdb
  netinet_in
  parse-datetime
  progname
  read-file
  reallocarray
  recv
  recvfrom
  secure_getenv
  select
  send
  sendto
  servent
  setsockopt
  shutdown
  snprintf
  socket
  sockets
  socklen
  stdint
  stpcpy
  strcase
  strdup-posix
  strndup
  strtok_r
  strverscmp
  sys_socket
  sys_stat
  sys_types
  threadlib
  time_r
  unistd
  valgrind-tests
  vasprintf
  verify
  vsnprintf
  xalloc
  xalloc-oversized
  xlist
  xsize
])
gl_AVOID([])
gl_SOURCE_BASE([src/gl])
gl_M4_BASE([src/gl/m4])
gl_PO_BASE([])
gl_DOC_BASE([doc])
gl_TESTS_BASE([src/gl/tests])
gl_WITH_TESTS
gl_LIB([libgnu_gpl])
gl_MAKEFILE_NAME([])
gl_LIBTOOL
gl_MACRO_PREFIX([ggl])
gl_PO_DOMAIN([])
gl_WITNESS_C_MACRO([])
gl_VC_FILES([false])
