#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/','m','s',
        'c','h','r','e','i','b','e','r','/','P','r','o','j','e','c','t','/','b',
        'u','i','l','d','r','o','o','t','-','2','0','1','6','.','0','5','/','o',
        'u','t','p','u','t','/','h','o','s','t','/','u','s','r','/','b','i','n',
        '/','s','h','4','a','-','b','u','i','l','d','r','o','o','t','-','l','i',
        'n','u','x','-','g','n','u','-','g','c','c',' ','-','I','.',' ','-','I',
        '.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',' ','-',
        'f','P','I','C',' ','-','D','O','P','E','N','S','S','L','_','P','I','C',
        ' ','-','D','Z','L','I','B','_','S','H','A','R','E','D',' ','-','D','Z',
        'L','I','B',' ','-','D','O','P','E','N','S','S','L','_','T','H','R','E',
        'A','D','S',' ','-','D','_','R','E','E','N','T','R','A','N','T',' ','-',
        'D','D','S','O','_','D','L','F','C','N',' ','-','D','H','A','V','E','_',
        'D','L','F','C','N','_','H',' ','-','D','_','L','A','R','G','E','F','I',
        'L','E','_','S','O','U','R','C','E',' ','-','D','_','L','A','R','G','E',
        'F','I','L','E','6','4','_','S','O','U','R','C','E',' ','-','D','_','F',
        'I','L','E','_','O','F','F','S','E','T','_','B','I','T','S','=','6','4',
        ' ',' ','-','O','s',' ',' ','-','f','o','m','i','t','-','f','r','a','m',
        'e','-','p','o','i','n','t','e','r',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: linux-generic32"
    #define DATE "built on: Fri May  3 12:43:23 2019"
#endif
