# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_audit', [dirname(__file__)])
        except ImportError:
            import _audit
            return _audit
        if fp is not None:
            try:
                _mod = imp.load_module('_audit', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _audit = swig_import_helper()
    del swig_import_helper
else:
    import _audit
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_audit.AUDIT_GET_swigconstant(_audit)
AUDIT_GET = _audit.AUDIT_GET

_audit.AUDIT_SET_swigconstant(_audit)
AUDIT_SET = _audit.AUDIT_SET

_audit.AUDIT_LIST_swigconstant(_audit)
AUDIT_LIST = _audit.AUDIT_LIST

_audit.AUDIT_ADD_swigconstant(_audit)
AUDIT_ADD = _audit.AUDIT_ADD

_audit.AUDIT_DEL_swigconstant(_audit)
AUDIT_DEL = _audit.AUDIT_DEL

_audit.AUDIT_USER_swigconstant(_audit)
AUDIT_USER = _audit.AUDIT_USER

_audit.AUDIT_LOGIN_swigconstant(_audit)
AUDIT_LOGIN = _audit.AUDIT_LOGIN

_audit.AUDIT_WATCH_INS_swigconstant(_audit)
AUDIT_WATCH_INS = _audit.AUDIT_WATCH_INS

_audit.AUDIT_WATCH_REM_swigconstant(_audit)
AUDIT_WATCH_REM = _audit.AUDIT_WATCH_REM

_audit.AUDIT_WATCH_LIST_swigconstant(_audit)
AUDIT_WATCH_LIST = _audit.AUDIT_WATCH_LIST

_audit.AUDIT_SIGNAL_INFO_swigconstant(_audit)
AUDIT_SIGNAL_INFO = _audit.AUDIT_SIGNAL_INFO

_audit.AUDIT_ADD_RULE_swigconstant(_audit)
AUDIT_ADD_RULE = _audit.AUDIT_ADD_RULE

_audit.AUDIT_DEL_RULE_swigconstant(_audit)
AUDIT_DEL_RULE = _audit.AUDIT_DEL_RULE

_audit.AUDIT_LIST_RULES_swigconstant(_audit)
AUDIT_LIST_RULES = _audit.AUDIT_LIST_RULES

_audit.AUDIT_TRIM_swigconstant(_audit)
AUDIT_TRIM = _audit.AUDIT_TRIM

_audit.AUDIT_MAKE_EQUIV_swigconstant(_audit)
AUDIT_MAKE_EQUIV = _audit.AUDIT_MAKE_EQUIV

_audit.AUDIT_TTY_GET_swigconstant(_audit)
AUDIT_TTY_GET = _audit.AUDIT_TTY_GET

_audit.AUDIT_TTY_SET_swigconstant(_audit)
AUDIT_TTY_SET = _audit.AUDIT_TTY_SET

_audit.AUDIT_SET_FEATURE_swigconstant(_audit)
AUDIT_SET_FEATURE = _audit.AUDIT_SET_FEATURE

_audit.AUDIT_GET_FEATURE_swigconstant(_audit)
AUDIT_GET_FEATURE = _audit.AUDIT_GET_FEATURE

_audit.AUDIT_FIRST_USER_MSG_swigconstant(_audit)
AUDIT_FIRST_USER_MSG = _audit.AUDIT_FIRST_USER_MSG

_audit.AUDIT_USER_AVC_swigconstant(_audit)
AUDIT_USER_AVC = _audit.AUDIT_USER_AVC

_audit.AUDIT_USER_TTY_swigconstant(_audit)
AUDIT_USER_TTY = _audit.AUDIT_USER_TTY

_audit.AUDIT_LAST_USER_MSG_swigconstant(_audit)
AUDIT_LAST_USER_MSG = _audit.AUDIT_LAST_USER_MSG

_audit.AUDIT_FIRST_USER_MSG2_swigconstant(_audit)
AUDIT_FIRST_USER_MSG2 = _audit.AUDIT_FIRST_USER_MSG2

_audit.AUDIT_LAST_USER_MSG2_swigconstant(_audit)
AUDIT_LAST_USER_MSG2 = _audit.AUDIT_LAST_USER_MSG2

_audit.AUDIT_DAEMON_START_swigconstant(_audit)
AUDIT_DAEMON_START = _audit.AUDIT_DAEMON_START

_audit.AUDIT_DAEMON_END_swigconstant(_audit)
AUDIT_DAEMON_END = _audit.AUDIT_DAEMON_END

_audit.AUDIT_DAEMON_ABORT_swigconstant(_audit)
AUDIT_DAEMON_ABORT = _audit.AUDIT_DAEMON_ABORT

_audit.AUDIT_DAEMON_CONFIG_swigconstant(_audit)
AUDIT_DAEMON_CONFIG = _audit.AUDIT_DAEMON_CONFIG

_audit.AUDIT_SYSCALL_swigconstant(_audit)
AUDIT_SYSCALL = _audit.AUDIT_SYSCALL

_audit.AUDIT_PATH_swigconstant(_audit)
AUDIT_PATH = _audit.AUDIT_PATH

_audit.AUDIT_IPC_swigconstant(_audit)
AUDIT_IPC = _audit.AUDIT_IPC

_audit.AUDIT_SOCKETCALL_swigconstant(_audit)
AUDIT_SOCKETCALL = _audit.AUDIT_SOCKETCALL

_audit.AUDIT_CONFIG_CHANGE_swigconstant(_audit)
AUDIT_CONFIG_CHANGE = _audit.AUDIT_CONFIG_CHANGE

_audit.AUDIT_SOCKADDR_swigconstant(_audit)
AUDIT_SOCKADDR = _audit.AUDIT_SOCKADDR

_audit.AUDIT_CWD_swigconstant(_audit)
AUDIT_CWD = _audit.AUDIT_CWD

_audit.AUDIT_EXECVE_swigconstant(_audit)
AUDIT_EXECVE = _audit.AUDIT_EXECVE

_audit.AUDIT_IPC_SET_PERM_swigconstant(_audit)
AUDIT_IPC_SET_PERM = _audit.AUDIT_IPC_SET_PERM

_audit.AUDIT_MQ_OPEN_swigconstant(_audit)
AUDIT_MQ_OPEN = _audit.AUDIT_MQ_OPEN

_audit.AUDIT_MQ_SENDRECV_swigconstant(_audit)
AUDIT_MQ_SENDRECV = _audit.AUDIT_MQ_SENDRECV

_audit.AUDIT_MQ_NOTIFY_swigconstant(_audit)
AUDIT_MQ_NOTIFY = _audit.AUDIT_MQ_NOTIFY

_audit.AUDIT_MQ_GETSETATTR_swigconstant(_audit)
AUDIT_MQ_GETSETATTR = _audit.AUDIT_MQ_GETSETATTR

_audit.AUDIT_KERNEL_OTHER_swigconstant(_audit)
AUDIT_KERNEL_OTHER = _audit.AUDIT_KERNEL_OTHER

_audit.AUDIT_FD_PAIR_swigconstant(_audit)
AUDIT_FD_PAIR = _audit.AUDIT_FD_PAIR

_audit.AUDIT_OBJ_PID_swigconstant(_audit)
AUDIT_OBJ_PID = _audit.AUDIT_OBJ_PID

_audit.AUDIT_TTY_swigconstant(_audit)
AUDIT_TTY = _audit.AUDIT_TTY

_audit.AUDIT_EOE_swigconstant(_audit)
AUDIT_EOE = _audit.AUDIT_EOE

_audit.AUDIT_BPRM_FCAPS_swigconstant(_audit)
AUDIT_BPRM_FCAPS = _audit.AUDIT_BPRM_FCAPS

_audit.AUDIT_CAPSET_swigconstant(_audit)
AUDIT_CAPSET = _audit.AUDIT_CAPSET

_audit.AUDIT_MMAP_swigconstant(_audit)
AUDIT_MMAP = _audit.AUDIT_MMAP

_audit.AUDIT_NETFILTER_PKT_swigconstant(_audit)
AUDIT_NETFILTER_PKT = _audit.AUDIT_NETFILTER_PKT

_audit.AUDIT_NETFILTER_CFG_swigconstant(_audit)
AUDIT_NETFILTER_CFG = _audit.AUDIT_NETFILTER_CFG

_audit.AUDIT_SECCOMP_swigconstant(_audit)
AUDIT_SECCOMP = _audit.AUDIT_SECCOMP

_audit.AUDIT_PROCTITLE_swigconstant(_audit)
AUDIT_PROCTITLE = _audit.AUDIT_PROCTITLE

_audit.AUDIT_FEATURE_CHANGE_swigconstant(_audit)
AUDIT_FEATURE_CHANGE = _audit.AUDIT_FEATURE_CHANGE

_audit.AUDIT_AVC_swigconstant(_audit)
AUDIT_AVC = _audit.AUDIT_AVC

_audit.AUDIT_SELINUX_ERR_swigconstant(_audit)
AUDIT_SELINUX_ERR = _audit.AUDIT_SELINUX_ERR

_audit.AUDIT_AVC_PATH_swigconstant(_audit)
AUDIT_AVC_PATH = _audit.AUDIT_AVC_PATH

_audit.AUDIT_MAC_POLICY_LOAD_swigconstant(_audit)
AUDIT_MAC_POLICY_LOAD = _audit.AUDIT_MAC_POLICY_LOAD

_audit.AUDIT_MAC_STATUS_swigconstant(_audit)
AUDIT_MAC_STATUS = _audit.AUDIT_MAC_STATUS

_audit.AUDIT_MAC_CONFIG_CHANGE_swigconstant(_audit)
AUDIT_MAC_CONFIG_CHANGE = _audit.AUDIT_MAC_CONFIG_CHANGE

_audit.AUDIT_MAC_UNLBL_ALLOW_swigconstant(_audit)
AUDIT_MAC_UNLBL_ALLOW = _audit.AUDIT_MAC_UNLBL_ALLOW

_audit.AUDIT_MAC_CIPSOV4_ADD_swigconstant(_audit)
AUDIT_MAC_CIPSOV4_ADD = _audit.AUDIT_MAC_CIPSOV4_ADD

_audit.AUDIT_MAC_CIPSOV4_DEL_swigconstant(_audit)
AUDIT_MAC_CIPSOV4_DEL = _audit.AUDIT_MAC_CIPSOV4_DEL

_audit.AUDIT_MAC_MAP_ADD_swigconstant(_audit)
AUDIT_MAC_MAP_ADD = _audit.AUDIT_MAC_MAP_ADD

_audit.AUDIT_MAC_MAP_DEL_swigconstant(_audit)
AUDIT_MAC_MAP_DEL = _audit.AUDIT_MAC_MAP_DEL

_audit.AUDIT_MAC_IPSEC_ADDSA_swigconstant(_audit)
AUDIT_MAC_IPSEC_ADDSA = _audit.AUDIT_MAC_IPSEC_ADDSA

_audit.AUDIT_MAC_IPSEC_DELSA_swigconstant(_audit)
AUDIT_MAC_IPSEC_DELSA = _audit.AUDIT_MAC_IPSEC_DELSA

_audit.AUDIT_MAC_IPSEC_ADDSPD_swigconstant(_audit)
AUDIT_MAC_IPSEC_ADDSPD = _audit.AUDIT_MAC_IPSEC_ADDSPD

_audit.AUDIT_MAC_IPSEC_DELSPD_swigconstant(_audit)
AUDIT_MAC_IPSEC_DELSPD = _audit.AUDIT_MAC_IPSEC_DELSPD

_audit.AUDIT_MAC_IPSEC_EVENT_swigconstant(_audit)
AUDIT_MAC_IPSEC_EVENT = _audit.AUDIT_MAC_IPSEC_EVENT

_audit.AUDIT_MAC_UNLBL_STCADD_swigconstant(_audit)
AUDIT_MAC_UNLBL_STCADD = _audit.AUDIT_MAC_UNLBL_STCADD

_audit.AUDIT_MAC_UNLBL_STCDEL_swigconstant(_audit)
AUDIT_MAC_UNLBL_STCDEL = _audit.AUDIT_MAC_UNLBL_STCDEL

_audit.AUDIT_FIRST_KERN_ANOM_MSG_swigconstant(_audit)
AUDIT_FIRST_KERN_ANOM_MSG = _audit.AUDIT_FIRST_KERN_ANOM_MSG

_audit.AUDIT_LAST_KERN_ANOM_MSG_swigconstant(_audit)
AUDIT_LAST_KERN_ANOM_MSG = _audit.AUDIT_LAST_KERN_ANOM_MSG

_audit.AUDIT_ANOM_PROMISCUOUS_swigconstant(_audit)
AUDIT_ANOM_PROMISCUOUS = _audit.AUDIT_ANOM_PROMISCUOUS

_audit.AUDIT_ANOM_ABEND_swigconstant(_audit)
AUDIT_ANOM_ABEND = _audit.AUDIT_ANOM_ABEND

_audit.AUDIT_ANOM_LINK_swigconstant(_audit)
AUDIT_ANOM_LINK = _audit.AUDIT_ANOM_LINK

_audit.AUDIT_INTEGRITY_DATA_swigconstant(_audit)
AUDIT_INTEGRITY_DATA = _audit.AUDIT_INTEGRITY_DATA

_audit.AUDIT_INTEGRITY_METADATA_swigconstant(_audit)
AUDIT_INTEGRITY_METADATA = _audit.AUDIT_INTEGRITY_METADATA

_audit.AUDIT_INTEGRITY_STATUS_swigconstant(_audit)
AUDIT_INTEGRITY_STATUS = _audit.AUDIT_INTEGRITY_STATUS

_audit.AUDIT_INTEGRITY_HASH_swigconstant(_audit)
AUDIT_INTEGRITY_HASH = _audit.AUDIT_INTEGRITY_HASH

_audit.AUDIT_INTEGRITY_PCR_swigconstant(_audit)
AUDIT_INTEGRITY_PCR = _audit.AUDIT_INTEGRITY_PCR

_audit.AUDIT_INTEGRITY_RULE_swigconstant(_audit)
AUDIT_INTEGRITY_RULE = _audit.AUDIT_INTEGRITY_RULE

_audit.AUDIT_KERNEL_swigconstant(_audit)
AUDIT_KERNEL = _audit.AUDIT_KERNEL

_audit.AUDIT_FILTER_USER_swigconstant(_audit)
AUDIT_FILTER_USER = _audit.AUDIT_FILTER_USER

_audit.AUDIT_FILTER_TASK_swigconstant(_audit)
AUDIT_FILTER_TASK = _audit.AUDIT_FILTER_TASK

_audit.AUDIT_FILTER_ENTRY_swigconstant(_audit)
AUDIT_FILTER_ENTRY = _audit.AUDIT_FILTER_ENTRY

_audit.AUDIT_FILTER_WATCH_swigconstant(_audit)
AUDIT_FILTER_WATCH = _audit.AUDIT_FILTER_WATCH

_audit.AUDIT_FILTER_EXIT_swigconstant(_audit)
AUDIT_FILTER_EXIT = _audit.AUDIT_FILTER_EXIT

_audit.AUDIT_FILTER_TYPE_swigconstant(_audit)
AUDIT_FILTER_TYPE = _audit.AUDIT_FILTER_TYPE

_audit.AUDIT_NR_FILTERS_swigconstant(_audit)
AUDIT_NR_FILTERS = _audit.AUDIT_NR_FILTERS

_audit.AUDIT_FILTER_PREPEND_swigconstant(_audit)
AUDIT_FILTER_PREPEND = _audit.AUDIT_FILTER_PREPEND

_audit.AUDIT_NEVER_swigconstant(_audit)
AUDIT_NEVER = _audit.AUDIT_NEVER

_audit.AUDIT_POSSIBLE_swigconstant(_audit)
AUDIT_POSSIBLE = _audit.AUDIT_POSSIBLE

_audit.AUDIT_ALWAYS_swigconstant(_audit)
AUDIT_ALWAYS = _audit.AUDIT_ALWAYS

_audit.AUDIT_MAX_FIELDS_swigconstant(_audit)
AUDIT_MAX_FIELDS = _audit.AUDIT_MAX_FIELDS

_audit.AUDIT_MAX_KEY_LEN_swigconstant(_audit)
AUDIT_MAX_KEY_LEN = _audit.AUDIT_MAX_KEY_LEN

_audit.AUDIT_BITMASK_SIZE_swigconstant(_audit)
AUDIT_BITMASK_SIZE = _audit.AUDIT_BITMASK_SIZE

_audit.AUDIT_SYSCALL_CLASSES_swigconstant(_audit)
AUDIT_SYSCALL_CLASSES = _audit.AUDIT_SYSCALL_CLASSES

_audit.AUDIT_CLASS_DIR_WRITE_swigconstant(_audit)
AUDIT_CLASS_DIR_WRITE = _audit.AUDIT_CLASS_DIR_WRITE

_audit.AUDIT_CLASS_DIR_WRITE_32_swigconstant(_audit)
AUDIT_CLASS_DIR_WRITE_32 = _audit.AUDIT_CLASS_DIR_WRITE_32

_audit.AUDIT_CLASS_CHATTR_swigconstant(_audit)
AUDIT_CLASS_CHATTR = _audit.AUDIT_CLASS_CHATTR

_audit.AUDIT_CLASS_CHATTR_32_swigconstant(_audit)
AUDIT_CLASS_CHATTR_32 = _audit.AUDIT_CLASS_CHATTR_32

_audit.AUDIT_CLASS_READ_swigconstant(_audit)
AUDIT_CLASS_READ = _audit.AUDIT_CLASS_READ

_audit.AUDIT_CLASS_READ_32_swigconstant(_audit)
AUDIT_CLASS_READ_32 = _audit.AUDIT_CLASS_READ_32

_audit.AUDIT_CLASS_WRITE_swigconstant(_audit)
AUDIT_CLASS_WRITE = _audit.AUDIT_CLASS_WRITE

_audit.AUDIT_CLASS_WRITE_32_swigconstant(_audit)
AUDIT_CLASS_WRITE_32 = _audit.AUDIT_CLASS_WRITE_32

_audit.AUDIT_CLASS_SIGNAL_swigconstant(_audit)
AUDIT_CLASS_SIGNAL = _audit.AUDIT_CLASS_SIGNAL

_audit.AUDIT_CLASS_SIGNAL_32_swigconstant(_audit)
AUDIT_CLASS_SIGNAL_32 = _audit.AUDIT_CLASS_SIGNAL_32

_audit.AUDIT_UNUSED_BITS_swigconstant(_audit)
AUDIT_UNUSED_BITS = _audit.AUDIT_UNUSED_BITS

_audit.AUDIT_COMPARE_UID_TO_OBJ_UID_swigconstant(_audit)
AUDIT_COMPARE_UID_TO_OBJ_UID = _audit.AUDIT_COMPARE_UID_TO_OBJ_UID

_audit.AUDIT_COMPARE_GID_TO_OBJ_GID_swigconstant(_audit)
AUDIT_COMPARE_GID_TO_OBJ_GID = _audit.AUDIT_COMPARE_GID_TO_OBJ_GID

_audit.AUDIT_COMPARE_EUID_TO_OBJ_UID_swigconstant(_audit)
AUDIT_COMPARE_EUID_TO_OBJ_UID = _audit.AUDIT_COMPARE_EUID_TO_OBJ_UID

_audit.AUDIT_COMPARE_EGID_TO_OBJ_GID_swigconstant(_audit)
AUDIT_COMPARE_EGID_TO_OBJ_GID = _audit.AUDIT_COMPARE_EGID_TO_OBJ_GID

_audit.AUDIT_COMPARE_AUID_TO_OBJ_UID_swigconstant(_audit)
AUDIT_COMPARE_AUID_TO_OBJ_UID = _audit.AUDIT_COMPARE_AUID_TO_OBJ_UID

_audit.AUDIT_COMPARE_SUID_TO_OBJ_UID_swigconstant(_audit)
AUDIT_COMPARE_SUID_TO_OBJ_UID = _audit.AUDIT_COMPARE_SUID_TO_OBJ_UID

_audit.AUDIT_COMPARE_SGID_TO_OBJ_GID_swigconstant(_audit)
AUDIT_COMPARE_SGID_TO_OBJ_GID = _audit.AUDIT_COMPARE_SGID_TO_OBJ_GID

_audit.AUDIT_COMPARE_FSUID_TO_OBJ_UID_swigconstant(_audit)
AUDIT_COMPARE_FSUID_TO_OBJ_UID = _audit.AUDIT_COMPARE_FSUID_TO_OBJ_UID

_audit.AUDIT_COMPARE_FSGID_TO_OBJ_GID_swigconstant(_audit)
AUDIT_COMPARE_FSGID_TO_OBJ_GID = _audit.AUDIT_COMPARE_FSGID_TO_OBJ_GID

_audit.AUDIT_COMPARE_UID_TO_AUID_swigconstant(_audit)
AUDIT_COMPARE_UID_TO_AUID = _audit.AUDIT_COMPARE_UID_TO_AUID

_audit.AUDIT_COMPARE_UID_TO_EUID_swigconstant(_audit)
AUDIT_COMPARE_UID_TO_EUID = _audit.AUDIT_COMPARE_UID_TO_EUID

_audit.AUDIT_COMPARE_UID_TO_FSUID_swigconstant(_audit)
AUDIT_COMPARE_UID_TO_FSUID = _audit.AUDIT_COMPARE_UID_TO_FSUID

_audit.AUDIT_COMPARE_UID_TO_SUID_swigconstant(_audit)
AUDIT_COMPARE_UID_TO_SUID = _audit.AUDIT_COMPARE_UID_TO_SUID

_audit.AUDIT_COMPARE_AUID_TO_FSUID_swigconstant(_audit)
AUDIT_COMPARE_AUID_TO_FSUID = _audit.AUDIT_COMPARE_AUID_TO_FSUID

_audit.AUDIT_COMPARE_AUID_TO_SUID_swigconstant(_audit)
AUDIT_COMPARE_AUID_TO_SUID = _audit.AUDIT_COMPARE_AUID_TO_SUID

_audit.AUDIT_COMPARE_AUID_TO_EUID_swigconstant(_audit)
AUDIT_COMPARE_AUID_TO_EUID = _audit.AUDIT_COMPARE_AUID_TO_EUID

_audit.AUDIT_COMPARE_EUID_TO_SUID_swigconstant(_audit)
AUDIT_COMPARE_EUID_TO_SUID = _audit.AUDIT_COMPARE_EUID_TO_SUID

_audit.AUDIT_COMPARE_EUID_TO_FSUID_swigconstant(_audit)
AUDIT_COMPARE_EUID_TO_FSUID = _audit.AUDIT_COMPARE_EUID_TO_FSUID

_audit.AUDIT_COMPARE_SUID_TO_FSUID_swigconstant(_audit)
AUDIT_COMPARE_SUID_TO_FSUID = _audit.AUDIT_COMPARE_SUID_TO_FSUID

_audit.AUDIT_COMPARE_GID_TO_EGID_swigconstant(_audit)
AUDIT_COMPARE_GID_TO_EGID = _audit.AUDIT_COMPARE_GID_TO_EGID

_audit.AUDIT_COMPARE_GID_TO_FSGID_swigconstant(_audit)
AUDIT_COMPARE_GID_TO_FSGID = _audit.AUDIT_COMPARE_GID_TO_FSGID

_audit.AUDIT_COMPARE_GID_TO_SGID_swigconstant(_audit)
AUDIT_COMPARE_GID_TO_SGID = _audit.AUDIT_COMPARE_GID_TO_SGID

_audit.AUDIT_COMPARE_EGID_TO_FSGID_swigconstant(_audit)
AUDIT_COMPARE_EGID_TO_FSGID = _audit.AUDIT_COMPARE_EGID_TO_FSGID

_audit.AUDIT_COMPARE_EGID_TO_SGID_swigconstant(_audit)
AUDIT_COMPARE_EGID_TO_SGID = _audit.AUDIT_COMPARE_EGID_TO_SGID

_audit.AUDIT_COMPARE_SGID_TO_FSGID_swigconstant(_audit)
AUDIT_COMPARE_SGID_TO_FSGID = _audit.AUDIT_COMPARE_SGID_TO_FSGID

_audit.AUDIT_MAX_FIELD_COMPARE_swigconstant(_audit)
AUDIT_MAX_FIELD_COMPARE = _audit.AUDIT_MAX_FIELD_COMPARE

_audit.AUDIT_PID_swigconstant(_audit)
AUDIT_PID = _audit.AUDIT_PID

_audit.AUDIT_UID_swigconstant(_audit)
AUDIT_UID = _audit.AUDIT_UID

_audit.AUDIT_EUID_swigconstant(_audit)
AUDIT_EUID = _audit.AUDIT_EUID

_audit.AUDIT_SUID_swigconstant(_audit)
AUDIT_SUID = _audit.AUDIT_SUID

_audit.AUDIT_FSUID_swigconstant(_audit)
AUDIT_FSUID = _audit.AUDIT_FSUID

_audit.AUDIT_GID_swigconstant(_audit)
AUDIT_GID = _audit.AUDIT_GID

_audit.AUDIT_EGID_swigconstant(_audit)
AUDIT_EGID = _audit.AUDIT_EGID

_audit.AUDIT_SGID_swigconstant(_audit)
AUDIT_SGID = _audit.AUDIT_SGID

_audit.AUDIT_FSGID_swigconstant(_audit)
AUDIT_FSGID = _audit.AUDIT_FSGID

_audit.AUDIT_LOGINUID_swigconstant(_audit)
AUDIT_LOGINUID = _audit.AUDIT_LOGINUID

_audit.AUDIT_PERS_swigconstant(_audit)
AUDIT_PERS = _audit.AUDIT_PERS

_audit.AUDIT_ARCH_swigconstant(_audit)
AUDIT_ARCH = _audit.AUDIT_ARCH

_audit.AUDIT_MSGTYPE_swigconstant(_audit)
AUDIT_MSGTYPE = _audit.AUDIT_MSGTYPE

_audit.AUDIT_SUBJ_USER_swigconstant(_audit)
AUDIT_SUBJ_USER = _audit.AUDIT_SUBJ_USER

_audit.AUDIT_SUBJ_ROLE_swigconstant(_audit)
AUDIT_SUBJ_ROLE = _audit.AUDIT_SUBJ_ROLE

_audit.AUDIT_SUBJ_TYPE_swigconstant(_audit)
AUDIT_SUBJ_TYPE = _audit.AUDIT_SUBJ_TYPE

_audit.AUDIT_SUBJ_SEN_swigconstant(_audit)
AUDIT_SUBJ_SEN = _audit.AUDIT_SUBJ_SEN

_audit.AUDIT_SUBJ_CLR_swigconstant(_audit)
AUDIT_SUBJ_CLR = _audit.AUDIT_SUBJ_CLR

_audit.AUDIT_PPID_swigconstant(_audit)
AUDIT_PPID = _audit.AUDIT_PPID

_audit.AUDIT_OBJ_USER_swigconstant(_audit)
AUDIT_OBJ_USER = _audit.AUDIT_OBJ_USER

_audit.AUDIT_OBJ_ROLE_swigconstant(_audit)
AUDIT_OBJ_ROLE = _audit.AUDIT_OBJ_ROLE

_audit.AUDIT_OBJ_TYPE_swigconstant(_audit)
AUDIT_OBJ_TYPE = _audit.AUDIT_OBJ_TYPE

_audit.AUDIT_OBJ_LEV_LOW_swigconstant(_audit)
AUDIT_OBJ_LEV_LOW = _audit.AUDIT_OBJ_LEV_LOW

_audit.AUDIT_OBJ_LEV_HIGH_swigconstant(_audit)
AUDIT_OBJ_LEV_HIGH = _audit.AUDIT_OBJ_LEV_HIGH

_audit.AUDIT_LOGINUID_SET_swigconstant(_audit)
AUDIT_LOGINUID_SET = _audit.AUDIT_LOGINUID_SET

_audit.AUDIT_DEVMAJOR_swigconstant(_audit)
AUDIT_DEVMAJOR = _audit.AUDIT_DEVMAJOR

_audit.AUDIT_DEVMINOR_swigconstant(_audit)
AUDIT_DEVMINOR = _audit.AUDIT_DEVMINOR

_audit.AUDIT_INODE_swigconstant(_audit)
AUDIT_INODE = _audit.AUDIT_INODE

_audit.AUDIT_EXIT_swigconstant(_audit)
AUDIT_EXIT = _audit.AUDIT_EXIT

_audit.AUDIT_SUCCESS_swigconstant(_audit)
AUDIT_SUCCESS = _audit.AUDIT_SUCCESS

_audit.AUDIT_WATCH_swigconstant(_audit)
AUDIT_WATCH = _audit.AUDIT_WATCH

_audit.AUDIT_PERM_swigconstant(_audit)
AUDIT_PERM = _audit.AUDIT_PERM

_audit.AUDIT_DIR_swigconstant(_audit)
AUDIT_DIR = _audit.AUDIT_DIR

_audit.AUDIT_FILETYPE_swigconstant(_audit)
AUDIT_FILETYPE = _audit.AUDIT_FILETYPE

_audit.AUDIT_OBJ_UID_swigconstant(_audit)
AUDIT_OBJ_UID = _audit.AUDIT_OBJ_UID

_audit.AUDIT_OBJ_GID_swigconstant(_audit)
AUDIT_OBJ_GID = _audit.AUDIT_OBJ_GID

_audit.AUDIT_FIELD_COMPARE_swigconstant(_audit)
AUDIT_FIELD_COMPARE = _audit.AUDIT_FIELD_COMPARE

_audit.AUDIT_ARG0_swigconstant(_audit)
AUDIT_ARG0 = _audit.AUDIT_ARG0

_audit.AUDIT_ARG1_swigconstant(_audit)
AUDIT_ARG1 = _audit.AUDIT_ARG1

_audit.AUDIT_ARG2_swigconstant(_audit)
AUDIT_ARG2 = _audit.AUDIT_ARG2

_audit.AUDIT_ARG3_swigconstant(_audit)
AUDIT_ARG3 = _audit.AUDIT_ARG3

_audit.AUDIT_FILTERKEY_swigconstant(_audit)
AUDIT_FILTERKEY = _audit.AUDIT_FILTERKEY

_audit.AUDIT_NEGATE_swigconstant(_audit)
AUDIT_NEGATE = _audit.AUDIT_NEGATE

_audit.AUDIT_BIT_MASK_swigconstant(_audit)
AUDIT_BIT_MASK = _audit.AUDIT_BIT_MASK

_audit.AUDIT_LESS_THAN_swigconstant(_audit)
AUDIT_LESS_THAN = _audit.AUDIT_LESS_THAN

_audit.AUDIT_GREATER_THAN_swigconstant(_audit)
AUDIT_GREATER_THAN = _audit.AUDIT_GREATER_THAN

_audit.AUDIT_NOT_EQUAL_swigconstant(_audit)
AUDIT_NOT_EQUAL = _audit.AUDIT_NOT_EQUAL

_audit.AUDIT_EQUAL_swigconstant(_audit)
AUDIT_EQUAL = _audit.AUDIT_EQUAL

_audit.AUDIT_BIT_TEST_swigconstant(_audit)
AUDIT_BIT_TEST = _audit.AUDIT_BIT_TEST

_audit.AUDIT_LESS_THAN_OR_EQUAL_swigconstant(_audit)
AUDIT_LESS_THAN_OR_EQUAL = _audit.AUDIT_LESS_THAN_OR_EQUAL

_audit.AUDIT_GREATER_THAN_OR_EQUAL_swigconstant(_audit)
AUDIT_GREATER_THAN_OR_EQUAL = _audit.AUDIT_GREATER_THAN_OR_EQUAL

_audit.AUDIT_OPERATORS_swigconstant(_audit)
AUDIT_OPERATORS = _audit.AUDIT_OPERATORS

_audit.Audit_equal_swigconstant(_audit)
Audit_equal = _audit.Audit_equal

_audit.Audit_not_equal_swigconstant(_audit)
Audit_not_equal = _audit.Audit_not_equal

_audit.Audit_bitmask_swigconstant(_audit)
Audit_bitmask = _audit.Audit_bitmask

_audit.Audit_bittest_swigconstant(_audit)
Audit_bittest = _audit.Audit_bittest

_audit.Audit_lt_swigconstant(_audit)
Audit_lt = _audit.Audit_lt

_audit.Audit_gt_swigconstant(_audit)
Audit_gt = _audit.Audit_gt

_audit.Audit_le_swigconstant(_audit)
Audit_le = _audit.Audit_le

_audit.Audit_ge_swigconstant(_audit)
Audit_ge = _audit.Audit_ge

_audit.Audit_bad_swigconstant(_audit)
Audit_bad = _audit.Audit_bad

_audit.AUDIT_STATUS_ENABLED_swigconstant(_audit)
AUDIT_STATUS_ENABLED = _audit.AUDIT_STATUS_ENABLED

_audit.AUDIT_STATUS_FAILURE_swigconstant(_audit)
AUDIT_STATUS_FAILURE = _audit.AUDIT_STATUS_FAILURE

_audit.AUDIT_STATUS_PID_swigconstant(_audit)
AUDIT_STATUS_PID = _audit.AUDIT_STATUS_PID

_audit.AUDIT_STATUS_RATE_LIMIT_swigconstant(_audit)
AUDIT_STATUS_RATE_LIMIT = _audit.AUDIT_STATUS_RATE_LIMIT

_audit.AUDIT_STATUS_BACKLOG_LIMIT_swigconstant(_audit)
AUDIT_STATUS_BACKLOG_LIMIT = _audit.AUDIT_STATUS_BACKLOG_LIMIT

_audit.AUDIT_STATUS_BACKLOG_WAIT_TIME_swigconstant(_audit)
AUDIT_STATUS_BACKLOG_WAIT_TIME = _audit.AUDIT_STATUS_BACKLOG_WAIT_TIME

_audit.AUDIT_FEATURE_BITMAP_BACKLOG_LIMIT_swigconstant(_audit)
AUDIT_FEATURE_BITMAP_BACKLOG_LIMIT = _audit.AUDIT_FEATURE_BITMAP_BACKLOG_LIMIT

_audit.AUDIT_FEATURE_BITMAP_BACKLOG_WAIT_TIME_swigconstant(_audit)
AUDIT_FEATURE_BITMAP_BACKLOG_WAIT_TIME = _audit.AUDIT_FEATURE_BITMAP_BACKLOG_WAIT_TIME

_audit.AUDIT_FEATURE_BITMAP_ALL_swigconstant(_audit)
AUDIT_FEATURE_BITMAP_ALL = _audit.AUDIT_FEATURE_BITMAP_ALL

_audit.AUDIT_VERSION_LATEST_swigconstant(_audit)
AUDIT_VERSION_LATEST = _audit.AUDIT_VERSION_LATEST

_audit.AUDIT_VERSION_BACKLOG_LIMIT_swigconstant(_audit)
AUDIT_VERSION_BACKLOG_LIMIT = _audit.AUDIT_VERSION_BACKLOG_LIMIT

_audit.AUDIT_VERSION_BACKLOG_WAIT_TIME_swigconstant(_audit)
AUDIT_VERSION_BACKLOG_WAIT_TIME = _audit.AUDIT_VERSION_BACKLOG_WAIT_TIME

_audit.AUDIT_FAIL_SILENT_swigconstant(_audit)
AUDIT_FAIL_SILENT = _audit.AUDIT_FAIL_SILENT

_audit.AUDIT_FAIL_PRINTK_swigconstant(_audit)
AUDIT_FAIL_PRINTK = _audit.AUDIT_FAIL_PRINTK

_audit.AUDIT_FAIL_PANIC_swigconstant(_audit)
AUDIT_FAIL_PANIC = _audit.AUDIT_FAIL_PANIC

_audit.__AUDIT_ARCH_CONVENTION_MASK_swigconstant(_audit)
__AUDIT_ARCH_CONVENTION_MASK = _audit.__AUDIT_ARCH_CONVENTION_MASK

_audit.__AUDIT_ARCH_CONVENTION_MIPS64_N32_swigconstant(_audit)
__AUDIT_ARCH_CONVENTION_MIPS64_N32 = _audit.__AUDIT_ARCH_CONVENTION_MIPS64_N32

_audit.__AUDIT_ARCH_64BIT_swigconstant(_audit)
__AUDIT_ARCH_64BIT = _audit.__AUDIT_ARCH_64BIT

_audit.__AUDIT_ARCH_LE_swigconstant(_audit)
__AUDIT_ARCH_LE = _audit.__AUDIT_ARCH_LE

_audit.AUDIT_PERM_EXEC_swigconstant(_audit)
AUDIT_PERM_EXEC = _audit.AUDIT_PERM_EXEC

_audit.AUDIT_PERM_WRITE_swigconstant(_audit)
AUDIT_PERM_WRITE = _audit.AUDIT_PERM_WRITE

_audit.AUDIT_PERM_READ_swigconstant(_audit)
AUDIT_PERM_READ = _audit.AUDIT_PERM_READ

_audit.AUDIT_PERM_ATTR_swigconstant(_audit)
AUDIT_PERM_ATTR = _audit.AUDIT_PERM_ATTR

_audit.AUDIT_MESSAGE_TEXT_MAX_swigconstant(_audit)
AUDIT_MESSAGE_TEXT_MAX = _audit.AUDIT_MESSAGE_TEXT_MAX

_audit.AUDIT_NLGRP_NONE_swigconstant(_audit)
AUDIT_NLGRP_NONE = _audit.AUDIT_NLGRP_NONE

_audit.AUDIT_NLGRP_READLOG_swigconstant(_audit)
AUDIT_NLGRP_READLOG = _audit.AUDIT_NLGRP_READLOG

_audit.__AUDIT_NLGRP_MAX_swigconstant(_audit)
__AUDIT_NLGRP_MAX = _audit.__AUDIT_NLGRP_MAX
class audit_status(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_status, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_status, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mask"] = _audit.audit_status_mask_set
    __swig_getmethods__["mask"] = _audit.audit_status_mask_get
    if _newclass:
        mask = _swig_property(_audit.audit_status_mask_get, _audit.audit_status_mask_set)
    __swig_setmethods__["enabled"] = _audit.audit_status_enabled_set
    __swig_getmethods__["enabled"] = _audit.audit_status_enabled_get
    if _newclass:
        enabled = _swig_property(_audit.audit_status_enabled_get, _audit.audit_status_enabled_set)
    __swig_setmethods__["failure"] = _audit.audit_status_failure_set
    __swig_getmethods__["failure"] = _audit.audit_status_failure_get
    if _newclass:
        failure = _swig_property(_audit.audit_status_failure_get, _audit.audit_status_failure_set)
    __swig_setmethods__["pid"] = _audit.audit_status_pid_set
    __swig_getmethods__["pid"] = _audit.audit_status_pid_get
    if _newclass:
        pid = _swig_property(_audit.audit_status_pid_get, _audit.audit_status_pid_set)
    __swig_setmethods__["rate_limit"] = _audit.audit_status_rate_limit_set
    __swig_getmethods__["rate_limit"] = _audit.audit_status_rate_limit_get
    if _newclass:
        rate_limit = _swig_property(_audit.audit_status_rate_limit_get, _audit.audit_status_rate_limit_set)
    __swig_setmethods__["backlog_limit"] = _audit.audit_status_backlog_limit_set
    __swig_getmethods__["backlog_limit"] = _audit.audit_status_backlog_limit_get
    if _newclass:
        backlog_limit = _swig_property(_audit.audit_status_backlog_limit_get, _audit.audit_status_backlog_limit_set)
    __swig_setmethods__["lost"] = _audit.audit_status_lost_set
    __swig_getmethods__["lost"] = _audit.audit_status_lost_get
    if _newclass:
        lost = _swig_property(_audit.audit_status_lost_get, _audit.audit_status_lost_set)
    __swig_setmethods__["backlog"] = _audit.audit_status_backlog_set
    __swig_getmethods__["backlog"] = _audit.audit_status_backlog_get
    if _newclass:
        backlog = _swig_property(_audit.audit_status_backlog_get, _audit.audit_status_backlog_set)
    __swig_setmethods__["version"] = _audit.audit_status_version_set
    __swig_getmethods__["version"] = _audit.audit_status_version_get
    if _newclass:
        version = _swig_property(_audit.audit_status_version_get, _audit.audit_status_version_set)
    __swig_setmethods__["feature_bitmap"] = _audit.audit_status_feature_bitmap_set
    __swig_getmethods__["feature_bitmap"] = _audit.audit_status_feature_bitmap_get
    if _newclass:
        feature_bitmap = _swig_property(_audit.audit_status_feature_bitmap_get, _audit.audit_status_feature_bitmap_set)
    __swig_setmethods__["backlog_wait_time"] = _audit.audit_status_backlog_wait_time_set
    __swig_getmethods__["backlog_wait_time"] = _audit.audit_status_backlog_wait_time_get
    if _newclass:
        backlog_wait_time = _swig_property(_audit.audit_status_backlog_wait_time_get, _audit.audit_status_backlog_wait_time_set)

    def __init__(self):
        this = _audit.new_audit_status()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_status
    __del__ = lambda self: None
audit_status_swigregister = _audit.audit_status_swigregister
audit_status_swigregister(audit_status)

class audit_features(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_features, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_features, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vers"] = _audit.audit_features_vers_set
    __swig_getmethods__["vers"] = _audit.audit_features_vers_get
    if _newclass:
        vers = _swig_property(_audit.audit_features_vers_get, _audit.audit_features_vers_set)
    __swig_setmethods__["mask"] = _audit.audit_features_mask_set
    __swig_getmethods__["mask"] = _audit.audit_features_mask_get
    if _newclass:
        mask = _swig_property(_audit.audit_features_mask_get, _audit.audit_features_mask_set)
    __swig_setmethods__["features"] = _audit.audit_features_features_set
    __swig_getmethods__["features"] = _audit.audit_features_features_get
    if _newclass:
        features = _swig_property(_audit.audit_features_features_get, _audit.audit_features_features_set)
    __swig_setmethods__["lock"] = _audit.audit_features_lock_set
    __swig_getmethods__["lock"] = _audit.audit_features_lock_get
    if _newclass:
        lock = _swig_property(_audit.audit_features_lock_get, _audit.audit_features_lock_set)

    def __init__(self):
        this = _audit.new_audit_features()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_features
    __del__ = lambda self: None
audit_features_swigregister = _audit.audit_features_swigregister
audit_features_swigregister(audit_features)

_audit.AUDIT_FEATURE_VERSION_swigconstant(_audit)
AUDIT_FEATURE_VERSION = _audit.AUDIT_FEATURE_VERSION


_audit.AUDIT_FEATURE_ONLY_UNSET_LOGINUID_swigconstant(_audit)
AUDIT_FEATURE_ONLY_UNSET_LOGINUID = _audit.AUDIT_FEATURE_ONLY_UNSET_LOGINUID

_audit.AUDIT_FEATURE_LOGINUID_IMMUTABLE_swigconstant(_audit)
AUDIT_FEATURE_LOGINUID_IMMUTABLE = _audit.AUDIT_FEATURE_LOGINUID_IMMUTABLE

_audit.AUDIT_LAST_FEATURE_swigconstant(_audit)
AUDIT_LAST_FEATURE = _audit.AUDIT_LAST_FEATURE
class audit_tty_status(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_tty_status, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_tty_status, name)
    __repr__ = _swig_repr
    __swig_setmethods__["enabled"] = _audit.audit_tty_status_enabled_set
    __swig_getmethods__["enabled"] = _audit.audit_tty_status_enabled_get
    if _newclass:
        enabled = _swig_property(_audit.audit_tty_status_enabled_get, _audit.audit_tty_status_enabled_set)
    __swig_setmethods__["log_passwd"] = _audit.audit_tty_status_log_passwd_set
    __swig_getmethods__["log_passwd"] = _audit.audit_tty_status_log_passwd_get
    if _newclass:
        log_passwd = _swig_property(_audit.audit_tty_status_log_passwd_get, _audit.audit_tty_status_log_passwd_set)

    def __init__(self):
        this = _audit.new_audit_tty_status()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_tty_status
    __del__ = lambda self: None
audit_tty_status_swigregister = _audit.audit_tty_status_swigregister
audit_tty_status_swigregister(audit_tty_status)

class audit_rule_data(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_rule_data, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_rule_data, name)
    __repr__ = _swig_repr
    __swig_setmethods__["flags"] = _audit.audit_rule_data_flags_set
    __swig_getmethods__["flags"] = _audit.audit_rule_data_flags_get
    if _newclass:
        flags = _swig_property(_audit.audit_rule_data_flags_get, _audit.audit_rule_data_flags_set)
    __swig_setmethods__["action"] = _audit.audit_rule_data_action_set
    __swig_getmethods__["action"] = _audit.audit_rule_data_action_get
    if _newclass:
        action = _swig_property(_audit.audit_rule_data_action_get, _audit.audit_rule_data_action_set)
    __swig_setmethods__["field_count"] = _audit.audit_rule_data_field_count_set
    __swig_getmethods__["field_count"] = _audit.audit_rule_data_field_count_get
    if _newclass:
        field_count = _swig_property(_audit.audit_rule_data_field_count_get, _audit.audit_rule_data_field_count_set)
    __swig_setmethods__["mask"] = _audit.audit_rule_data_mask_set
    __swig_getmethods__["mask"] = _audit.audit_rule_data_mask_get
    if _newclass:
        mask = _swig_property(_audit.audit_rule_data_mask_get, _audit.audit_rule_data_mask_set)
    __swig_setmethods__["fields"] = _audit.audit_rule_data_fields_set
    __swig_getmethods__["fields"] = _audit.audit_rule_data_fields_get
    if _newclass:
        fields = _swig_property(_audit.audit_rule_data_fields_get, _audit.audit_rule_data_fields_set)
    __swig_setmethods__["values"] = _audit.audit_rule_data_values_set
    __swig_getmethods__["values"] = _audit.audit_rule_data_values_get
    if _newclass:
        values = _swig_property(_audit.audit_rule_data_values_get, _audit.audit_rule_data_values_set)
    __swig_setmethods__["fieldflags"] = _audit.audit_rule_data_fieldflags_set
    __swig_getmethods__["fieldflags"] = _audit.audit_rule_data_fieldflags_get
    if _newclass:
        fieldflags = _swig_property(_audit.audit_rule_data_fieldflags_get, _audit.audit_rule_data_fieldflags_set)
    __swig_setmethods__["buflen"] = _audit.audit_rule_data_buflen_set
    __swig_getmethods__["buflen"] = _audit.audit_rule_data_buflen_get
    if _newclass:
        buflen = _swig_property(_audit.audit_rule_data_buflen_get, _audit.audit_rule_data_buflen_set)
    __swig_setmethods__["buf"] = _audit.audit_rule_data_buf_set
    __swig_getmethods__["buf"] = _audit.audit_rule_data_buf_get
    if _newclass:
        buf = _swig_property(_audit.audit_rule_data_buf_get, _audit.audit_rule_data_buf_set)

    def __init__(self):
        this = _audit.new_audit_rule_data()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_rule_data
    __del__ = lambda self: None
audit_rule_data_swigregister = _audit.audit_rule_data_swigregister
audit_rule_data_swigregister(audit_rule_data)


_audit._STDINT_H_swigconstant(_audit)
_STDINT_H = _audit._STDINT_H

_audit.INT8_MIN_swigconstant(_audit)
INT8_MIN = _audit.INT8_MIN

_audit.INT16_MIN_swigconstant(_audit)
INT16_MIN = _audit.INT16_MIN

_audit.INT32_MIN_swigconstant(_audit)
INT32_MIN = _audit.INT32_MIN

_audit.INT64_MIN_swigconstant(_audit)
INT64_MIN = _audit.INT64_MIN

_audit.INT8_MAX_swigconstant(_audit)
INT8_MAX = _audit.INT8_MAX

_audit.INT16_MAX_swigconstant(_audit)
INT16_MAX = _audit.INT16_MAX

_audit.INT32_MAX_swigconstant(_audit)
INT32_MAX = _audit.INT32_MAX

_audit.INT64_MAX_swigconstant(_audit)
INT64_MAX = _audit.INT64_MAX

_audit.UINT8_MAX_swigconstant(_audit)
UINT8_MAX = _audit.UINT8_MAX

_audit.UINT16_MAX_swigconstant(_audit)
UINT16_MAX = _audit.UINT16_MAX

_audit.UINT32_MAX_swigconstant(_audit)
UINT32_MAX = _audit.UINT32_MAX

_audit.UINT64_MAX_swigconstant(_audit)
UINT64_MAX = _audit.UINT64_MAX

_audit.INT_LEAST8_MIN_swigconstant(_audit)
INT_LEAST8_MIN = _audit.INT_LEAST8_MIN

_audit.INT_LEAST16_MIN_swigconstant(_audit)
INT_LEAST16_MIN = _audit.INT_LEAST16_MIN

_audit.INT_LEAST32_MIN_swigconstant(_audit)
INT_LEAST32_MIN = _audit.INT_LEAST32_MIN

_audit.INT_LEAST64_MIN_swigconstant(_audit)
INT_LEAST64_MIN = _audit.INT_LEAST64_MIN

_audit.INT_LEAST8_MAX_swigconstant(_audit)
INT_LEAST8_MAX = _audit.INT_LEAST8_MAX

_audit.INT_LEAST16_MAX_swigconstant(_audit)
INT_LEAST16_MAX = _audit.INT_LEAST16_MAX

_audit.INT_LEAST32_MAX_swigconstant(_audit)
INT_LEAST32_MAX = _audit.INT_LEAST32_MAX

_audit.INT_LEAST64_MAX_swigconstant(_audit)
INT_LEAST64_MAX = _audit.INT_LEAST64_MAX

_audit.UINT_LEAST8_MAX_swigconstant(_audit)
UINT_LEAST8_MAX = _audit.UINT_LEAST8_MAX

_audit.UINT_LEAST16_MAX_swigconstant(_audit)
UINT_LEAST16_MAX = _audit.UINT_LEAST16_MAX

_audit.UINT_LEAST32_MAX_swigconstant(_audit)
UINT_LEAST32_MAX = _audit.UINT_LEAST32_MAX

_audit.UINT_LEAST64_MAX_swigconstant(_audit)
UINT_LEAST64_MAX = _audit.UINT_LEAST64_MAX

_audit.INT_FAST8_MIN_swigconstant(_audit)
INT_FAST8_MIN = _audit.INT_FAST8_MIN

_audit.INT_FAST16_MIN_swigconstant(_audit)
INT_FAST16_MIN = _audit.INT_FAST16_MIN

_audit.INT_FAST32_MIN_swigconstant(_audit)
INT_FAST32_MIN = _audit.INT_FAST32_MIN

_audit.INT_FAST64_MIN_swigconstant(_audit)
INT_FAST64_MIN = _audit.INT_FAST64_MIN

_audit.INT_FAST8_MAX_swigconstant(_audit)
INT_FAST8_MAX = _audit.INT_FAST8_MAX

_audit.INT_FAST16_MAX_swigconstant(_audit)
INT_FAST16_MAX = _audit.INT_FAST16_MAX

_audit.INT_FAST32_MAX_swigconstant(_audit)
INT_FAST32_MAX = _audit.INT_FAST32_MAX

_audit.INT_FAST64_MAX_swigconstant(_audit)
INT_FAST64_MAX = _audit.INT_FAST64_MAX

_audit.UINT_FAST8_MAX_swigconstant(_audit)
UINT_FAST8_MAX = _audit.UINT_FAST8_MAX

_audit.UINT_FAST16_MAX_swigconstant(_audit)
UINT_FAST16_MAX = _audit.UINT_FAST16_MAX

_audit.UINT_FAST32_MAX_swigconstant(_audit)
UINT_FAST32_MAX = _audit.UINT_FAST32_MAX

_audit.UINT_FAST64_MAX_swigconstant(_audit)
UINT_FAST64_MAX = _audit.UINT_FAST64_MAX

_audit.INTPTR_MIN_swigconstant(_audit)
INTPTR_MIN = _audit.INTPTR_MIN

_audit.INTPTR_MAX_swigconstant(_audit)
INTPTR_MAX = _audit.INTPTR_MAX

_audit.UINTPTR_MAX_swigconstant(_audit)
UINTPTR_MAX = _audit.UINTPTR_MAX

_audit.INTMAX_MIN_swigconstant(_audit)
INTMAX_MIN = _audit.INTMAX_MIN

_audit.INTMAX_MAX_swigconstant(_audit)
INTMAX_MAX = _audit.INTMAX_MAX

_audit.UINTMAX_MAX_swigconstant(_audit)
UINTMAX_MAX = _audit.UINTMAX_MAX

_audit.PTRDIFF_MIN_swigconstant(_audit)
PTRDIFF_MIN = _audit.PTRDIFF_MIN

_audit.PTRDIFF_MAX_swigconstant(_audit)
PTRDIFF_MAX = _audit.PTRDIFF_MAX

_audit.SIG_ATOMIC_MIN_swigconstant(_audit)
SIG_ATOMIC_MIN = _audit.SIG_ATOMIC_MIN

_audit.SIG_ATOMIC_MAX_swigconstant(_audit)
SIG_ATOMIC_MAX = _audit.SIG_ATOMIC_MAX

_audit.SIZE_MAX_swigconstant(_audit)
SIZE_MAX = _audit.SIZE_MAX

_audit.WINT_MIN_swigconstant(_audit)
WINT_MIN = _audit.WINT_MIN

_audit.WINT_MAX_swigconstant(_audit)
WINT_MAX = _audit.WINT_MAX

_audit.AUDIT_USER_AUTH_swigconstant(_audit)
AUDIT_USER_AUTH = _audit.AUDIT_USER_AUTH

_audit.AUDIT_USER_ACCT_swigconstant(_audit)
AUDIT_USER_ACCT = _audit.AUDIT_USER_ACCT

_audit.AUDIT_USER_MGMT_swigconstant(_audit)
AUDIT_USER_MGMT = _audit.AUDIT_USER_MGMT

_audit.AUDIT_CRED_ACQ_swigconstant(_audit)
AUDIT_CRED_ACQ = _audit.AUDIT_CRED_ACQ

_audit.AUDIT_CRED_DISP_swigconstant(_audit)
AUDIT_CRED_DISP = _audit.AUDIT_CRED_DISP

_audit.AUDIT_USER_START_swigconstant(_audit)
AUDIT_USER_START = _audit.AUDIT_USER_START

_audit.AUDIT_USER_END_swigconstant(_audit)
AUDIT_USER_END = _audit.AUDIT_USER_END

_audit.AUDIT_USER_CHAUTHTOK_swigconstant(_audit)
AUDIT_USER_CHAUTHTOK = _audit.AUDIT_USER_CHAUTHTOK

_audit.AUDIT_USER_ERR_swigconstant(_audit)
AUDIT_USER_ERR = _audit.AUDIT_USER_ERR

_audit.AUDIT_CRED_REFR_swigconstant(_audit)
AUDIT_CRED_REFR = _audit.AUDIT_CRED_REFR

_audit.AUDIT_USYS_CONFIG_swigconstant(_audit)
AUDIT_USYS_CONFIG = _audit.AUDIT_USYS_CONFIG

_audit.AUDIT_USER_LOGIN_swigconstant(_audit)
AUDIT_USER_LOGIN = _audit.AUDIT_USER_LOGIN

_audit.AUDIT_USER_LOGOUT_swigconstant(_audit)
AUDIT_USER_LOGOUT = _audit.AUDIT_USER_LOGOUT

_audit.AUDIT_ADD_USER_swigconstant(_audit)
AUDIT_ADD_USER = _audit.AUDIT_ADD_USER

_audit.AUDIT_DEL_USER_swigconstant(_audit)
AUDIT_DEL_USER = _audit.AUDIT_DEL_USER

_audit.AUDIT_ADD_GROUP_swigconstant(_audit)
AUDIT_ADD_GROUP = _audit.AUDIT_ADD_GROUP

_audit.AUDIT_DEL_GROUP_swigconstant(_audit)
AUDIT_DEL_GROUP = _audit.AUDIT_DEL_GROUP

_audit.AUDIT_DAC_CHECK_swigconstant(_audit)
AUDIT_DAC_CHECK = _audit.AUDIT_DAC_CHECK

_audit.AUDIT_CHGRP_ID_swigconstant(_audit)
AUDIT_CHGRP_ID = _audit.AUDIT_CHGRP_ID

_audit.AUDIT_TEST_swigconstant(_audit)
AUDIT_TEST = _audit.AUDIT_TEST

_audit.AUDIT_TRUSTED_APP_swigconstant(_audit)
AUDIT_TRUSTED_APP = _audit.AUDIT_TRUSTED_APP

_audit.AUDIT_USER_SELINUX_ERR_swigconstant(_audit)
AUDIT_USER_SELINUX_ERR = _audit.AUDIT_USER_SELINUX_ERR

_audit.AUDIT_USER_CMD_swigconstant(_audit)
AUDIT_USER_CMD = _audit.AUDIT_USER_CMD

_audit.AUDIT_CHUSER_ID_swigconstant(_audit)
AUDIT_CHUSER_ID = _audit.AUDIT_CHUSER_ID

_audit.AUDIT_GRP_AUTH_swigconstant(_audit)
AUDIT_GRP_AUTH = _audit.AUDIT_GRP_AUTH

_audit.AUDIT_SYSTEM_BOOT_swigconstant(_audit)
AUDIT_SYSTEM_BOOT = _audit.AUDIT_SYSTEM_BOOT

_audit.AUDIT_SYSTEM_SHUTDOWN_swigconstant(_audit)
AUDIT_SYSTEM_SHUTDOWN = _audit.AUDIT_SYSTEM_SHUTDOWN

_audit.AUDIT_SYSTEM_RUNLEVEL_swigconstant(_audit)
AUDIT_SYSTEM_RUNLEVEL = _audit.AUDIT_SYSTEM_RUNLEVEL

_audit.AUDIT_SERVICE_START_swigconstant(_audit)
AUDIT_SERVICE_START = _audit.AUDIT_SERVICE_START

_audit.AUDIT_SERVICE_STOP_swigconstant(_audit)
AUDIT_SERVICE_STOP = _audit.AUDIT_SERVICE_STOP

_audit.AUDIT_GRP_MGMT_swigconstant(_audit)
AUDIT_GRP_MGMT = _audit.AUDIT_GRP_MGMT

_audit.AUDIT_GRP_CHAUTHTOK_swigconstant(_audit)
AUDIT_GRP_CHAUTHTOK = _audit.AUDIT_GRP_CHAUTHTOK

_audit.AUDIT_MAC_CHECK_swigconstant(_audit)
AUDIT_MAC_CHECK = _audit.AUDIT_MAC_CHECK

_audit.AUDIT_FIRST_DAEMON_swigconstant(_audit)
AUDIT_FIRST_DAEMON = _audit.AUDIT_FIRST_DAEMON

_audit.AUDIT_LAST_DAEMON_swigconstant(_audit)
AUDIT_LAST_DAEMON = _audit.AUDIT_LAST_DAEMON

_audit.AUDIT_DAEMON_RECONFIG_swigconstant(_audit)
AUDIT_DAEMON_RECONFIG = _audit.AUDIT_DAEMON_RECONFIG

_audit.AUDIT_DAEMON_ROTATE_swigconstant(_audit)
AUDIT_DAEMON_ROTATE = _audit.AUDIT_DAEMON_ROTATE

_audit.AUDIT_DAEMON_RESUME_swigconstant(_audit)
AUDIT_DAEMON_RESUME = _audit.AUDIT_DAEMON_RESUME

_audit.AUDIT_DAEMON_ACCEPT_swigconstant(_audit)
AUDIT_DAEMON_ACCEPT = _audit.AUDIT_DAEMON_ACCEPT

_audit.AUDIT_DAEMON_CLOSE_swigconstant(_audit)
AUDIT_DAEMON_CLOSE = _audit.AUDIT_DAEMON_CLOSE

_audit.AUDIT_FIRST_EVENT_swigconstant(_audit)
AUDIT_FIRST_EVENT = _audit.AUDIT_FIRST_EVENT

_audit.AUDIT_LAST_EVENT_swigconstant(_audit)
AUDIT_LAST_EVENT = _audit.AUDIT_LAST_EVENT

_audit.AUDIT_FIRST_SELINUX_swigconstant(_audit)
AUDIT_FIRST_SELINUX = _audit.AUDIT_FIRST_SELINUX

_audit.AUDIT_LAST_SELINUX_swigconstant(_audit)
AUDIT_LAST_SELINUX = _audit.AUDIT_LAST_SELINUX

_audit.AUDIT_FIRST_APPARMOR_swigconstant(_audit)
AUDIT_FIRST_APPARMOR = _audit.AUDIT_FIRST_APPARMOR

_audit.AUDIT_LAST_APPARMOR_swigconstant(_audit)
AUDIT_LAST_APPARMOR = _audit.AUDIT_LAST_APPARMOR

_audit.AUDIT_AA_swigconstant(_audit)
AUDIT_AA = _audit.AUDIT_AA

_audit.AUDIT_APPARMOR_AUDIT_swigconstant(_audit)
AUDIT_APPARMOR_AUDIT = _audit.AUDIT_APPARMOR_AUDIT

_audit.AUDIT_APPARMOR_ALLOWED_swigconstant(_audit)
AUDIT_APPARMOR_ALLOWED = _audit.AUDIT_APPARMOR_ALLOWED

_audit.AUDIT_APPARMOR_DENIED_swigconstant(_audit)
AUDIT_APPARMOR_DENIED = _audit.AUDIT_APPARMOR_DENIED

_audit.AUDIT_APPARMOR_HINT_swigconstant(_audit)
AUDIT_APPARMOR_HINT = _audit.AUDIT_APPARMOR_HINT

_audit.AUDIT_APPARMOR_STATUS_swigconstant(_audit)
AUDIT_APPARMOR_STATUS = _audit.AUDIT_APPARMOR_STATUS

_audit.AUDIT_APPARMOR_ERROR_swigconstant(_audit)
AUDIT_APPARMOR_ERROR = _audit.AUDIT_APPARMOR_ERROR

_audit.AUDIT_FIRST_KERN_CRYPTO_MSG_swigconstant(_audit)
AUDIT_FIRST_KERN_CRYPTO_MSG = _audit.AUDIT_FIRST_KERN_CRYPTO_MSG

_audit.AUDIT_LAST_KERN_CRYPTO_MSG_swigconstant(_audit)
AUDIT_LAST_KERN_CRYPTO_MSG = _audit.AUDIT_LAST_KERN_CRYPTO_MSG

_audit.AUDIT_INTEGRITY_FIRST_MSG_swigconstant(_audit)
AUDIT_INTEGRITY_FIRST_MSG = _audit.AUDIT_INTEGRITY_FIRST_MSG

_audit.AUDIT_INTEGRITY_LAST_MSG_swigconstant(_audit)
AUDIT_INTEGRITY_LAST_MSG = _audit.AUDIT_INTEGRITY_LAST_MSG

_audit.AUDIT_FIRST_ANOM_MSG_swigconstant(_audit)
AUDIT_FIRST_ANOM_MSG = _audit.AUDIT_FIRST_ANOM_MSG

_audit.AUDIT_LAST_ANOM_MSG_swigconstant(_audit)
AUDIT_LAST_ANOM_MSG = _audit.AUDIT_LAST_ANOM_MSG

_audit.AUDIT_ANOM_LOGIN_FAILURES_swigconstant(_audit)
AUDIT_ANOM_LOGIN_FAILURES = _audit.AUDIT_ANOM_LOGIN_FAILURES

_audit.AUDIT_ANOM_LOGIN_TIME_swigconstant(_audit)
AUDIT_ANOM_LOGIN_TIME = _audit.AUDIT_ANOM_LOGIN_TIME

_audit.AUDIT_ANOM_LOGIN_SESSIONS_swigconstant(_audit)
AUDIT_ANOM_LOGIN_SESSIONS = _audit.AUDIT_ANOM_LOGIN_SESSIONS

_audit.AUDIT_ANOM_LOGIN_ACCT_swigconstant(_audit)
AUDIT_ANOM_LOGIN_ACCT = _audit.AUDIT_ANOM_LOGIN_ACCT

_audit.AUDIT_ANOM_LOGIN_LOCATION_swigconstant(_audit)
AUDIT_ANOM_LOGIN_LOCATION = _audit.AUDIT_ANOM_LOGIN_LOCATION

_audit.AUDIT_ANOM_MAX_DAC_swigconstant(_audit)
AUDIT_ANOM_MAX_DAC = _audit.AUDIT_ANOM_MAX_DAC

_audit.AUDIT_ANOM_MAX_MAC_swigconstant(_audit)
AUDIT_ANOM_MAX_MAC = _audit.AUDIT_ANOM_MAX_MAC

_audit.AUDIT_ANOM_AMTU_FAIL_swigconstant(_audit)
AUDIT_ANOM_AMTU_FAIL = _audit.AUDIT_ANOM_AMTU_FAIL

_audit.AUDIT_ANOM_RBAC_FAIL_swigconstant(_audit)
AUDIT_ANOM_RBAC_FAIL = _audit.AUDIT_ANOM_RBAC_FAIL

_audit.AUDIT_ANOM_RBAC_INTEGRITY_FAIL_swigconstant(_audit)
AUDIT_ANOM_RBAC_INTEGRITY_FAIL = _audit.AUDIT_ANOM_RBAC_INTEGRITY_FAIL

_audit.AUDIT_ANOM_CRYPTO_FAIL_swigconstant(_audit)
AUDIT_ANOM_CRYPTO_FAIL = _audit.AUDIT_ANOM_CRYPTO_FAIL

_audit.AUDIT_ANOM_ACCESS_FS_swigconstant(_audit)
AUDIT_ANOM_ACCESS_FS = _audit.AUDIT_ANOM_ACCESS_FS

_audit.AUDIT_ANOM_EXEC_swigconstant(_audit)
AUDIT_ANOM_EXEC = _audit.AUDIT_ANOM_EXEC

_audit.AUDIT_ANOM_MK_EXEC_swigconstant(_audit)
AUDIT_ANOM_MK_EXEC = _audit.AUDIT_ANOM_MK_EXEC

_audit.AUDIT_ANOM_ADD_ACCT_swigconstant(_audit)
AUDIT_ANOM_ADD_ACCT = _audit.AUDIT_ANOM_ADD_ACCT

_audit.AUDIT_ANOM_DEL_ACCT_swigconstant(_audit)
AUDIT_ANOM_DEL_ACCT = _audit.AUDIT_ANOM_DEL_ACCT

_audit.AUDIT_ANOM_MOD_ACCT_swigconstant(_audit)
AUDIT_ANOM_MOD_ACCT = _audit.AUDIT_ANOM_MOD_ACCT

_audit.AUDIT_ANOM_ROOT_TRANS_swigconstant(_audit)
AUDIT_ANOM_ROOT_TRANS = _audit.AUDIT_ANOM_ROOT_TRANS

_audit.AUDIT_FIRST_ANOM_RESP_swigconstant(_audit)
AUDIT_FIRST_ANOM_RESP = _audit.AUDIT_FIRST_ANOM_RESP

_audit.AUDIT_LAST_ANOM_RESP_swigconstant(_audit)
AUDIT_LAST_ANOM_RESP = _audit.AUDIT_LAST_ANOM_RESP

_audit.AUDIT_RESP_ANOMALY_swigconstant(_audit)
AUDIT_RESP_ANOMALY = _audit.AUDIT_RESP_ANOMALY

_audit.AUDIT_RESP_ALERT_swigconstant(_audit)
AUDIT_RESP_ALERT = _audit.AUDIT_RESP_ALERT

_audit.AUDIT_RESP_KILL_PROC_swigconstant(_audit)
AUDIT_RESP_KILL_PROC = _audit.AUDIT_RESP_KILL_PROC

_audit.AUDIT_RESP_TERM_ACCESS_swigconstant(_audit)
AUDIT_RESP_TERM_ACCESS = _audit.AUDIT_RESP_TERM_ACCESS

_audit.AUDIT_RESP_ACCT_REMOTE_swigconstant(_audit)
AUDIT_RESP_ACCT_REMOTE = _audit.AUDIT_RESP_ACCT_REMOTE

_audit.AUDIT_RESP_ACCT_LOCK_TIMED_swigconstant(_audit)
AUDIT_RESP_ACCT_LOCK_TIMED = _audit.AUDIT_RESP_ACCT_LOCK_TIMED

_audit.AUDIT_RESP_ACCT_UNLOCK_TIMED_swigconstant(_audit)
AUDIT_RESP_ACCT_UNLOCK_TIMED = _audit.AUDIT_RESP_ACCT_UNLOCK_TIMED

_audit.AUDIT_RESP_ACCT_LOCK_swigconstant(_audit)
AUDIT_RESP_ACCT_LOCK = _audit.AUDIT_RESP_ACCT_LOCK

_audit.AUDIT_RESP_TERM_LOCK_swigconstant(_audit)
AUDIT_RESP_TERM_LOCK = _audit.AUDIT_RESP_TERM_LOCK

_audit.AUDIT_RESP_SEBOOL_swigconstant(_audit)
AUDIT_RESP_SEBOOL = _audit.AUDIT_RESP_SEBOOL

_audit.AUDIT_RESP_EXEC_swigconstant(_audit)
AUDIT_RESP_EXEC = _audit.AUDIT_RESP_EXEC

_audit.AUDIT_RESP_SINGLE_swigconstant(_audit)
AUDIT_RESP_SINGLE = _audit.AUDIT_RESP_SINGLE

_audit.AUDIT_RESP_HALT_swigconstant(_audit)
AUDIT_RESP_HALT = _audit.AUDIT_RESP_HALT

_audit.AUDIT_FIRST_USER_LSPP_MSG_swigconstant(_audit)
AUDIT_FIRST_USER_LSPP_MSG = _audit.AUDIT_FIRST_USER_LSPP_MSG

_audit.AUDIT_LAST_USER_LSPP_MSG_swigconstant(_audit)
AUDIT_LAST_USER_LSPP_MSG = _audit.AUDIT_LAST_USER_LSPP_MSG

_audit.AUDIT_USER_ROLE_CHANGE_swigconstant(_audit)
AUDIT_USER_ROLE_CHANGE = _audit.AUDIT_USER_ROLE_CHANGE

_audit.AUDIT_ROLE_ASSIGN_swigconstant(_audit)
AUDIT_ROLE_ASSIGN = _audit.AUDIT_ROLE_ASSIGN

_audit.AUDIT_ROLE_REMOVE_swigconstant(_audit)
AUDIT_ROLE_REMOVE = _audit.AUDIT_ROLE_REMOVE

_audit.AUDIT_LABEL_OVERRIDE_swigconstant(_audit)
AUDIT_LABEL_OVERRIDE = _audit.AUDIT_LABEL_OVERRIDE

_audit.AUDIT_LABEL_LEVEL_CHANGE_swigconstant(_audit)
AUDIT_LABEL_LEVEL_CHANGE = _audit.AUDIT_LABEL_LEVEL_CHANGE

_audit.AUDIT_USER_LABELED_EXPORT_swigconstant(_audit)
AUDIT_USER_LABELED_EXPORT = _audit.AUDIT_USER_LABELED_EXPORT

_audit.AUDIT_USER_UNLABELED_EXPORT_swigconstant(_audit)
AUDIT_USER_UNLABELED_EXPORT = _audit.AUDIT_USER_UNLABELED_EXPORT

_audit.AUDIT_DEV_ALLOC_swigconstant(_audit)
AUDIT_DEV_ALLOC = _audit.AUDIT_DEV_ALLOC

_audit.AUDIT_DEV_DEALLOC_swigconstant(_audit)
AUDIT_DEV_DEALLOC = _audit.AUDIT_DEV_DEALLOC

_audit.AUDIT_FS_RELABEL_swigconstant(_audit)
AUDIT_FS_RELABEL = _audit.AUDIT_FS_RELABEL

_audit.AUDIT_USER_MAC_POLICY_LOAD_swigconstant(_audit)
AUDIT_USER_MAC_POLICY_LOAD = _audit.AUDIT_USER_MAC_POLICY_LOAD

_audit.AUDIT_ROLE_MODIFY_swigconstant(_audit)
AUDIT_ROLE_MODIFY = _audit.AUDIT_ROLE_MODIFY

_audit.AUDIT_USER_MAC_CONFIG_CHANGE_swigconstant(_audit)
AUDIT_USER_MAC_CONFIG_CHANGE = _audit.AUDIT_USER_MAC_CONFIG_CHANGE

_audit.AUDIT_FIRST_CRYPTO_MSG_swigconstant(_audit)
AUDIT_FIRST_CRYPTO_MSG = _audit.AUDIT_FIRST_CRYPTO_MSG

_audit.AUDIT_CRYPTO_TEST_USER_swigconstant(_audit)
AUDIT_CRYPTO_TEST_USER = _audit.AUDIT_CRYPTO_TEST_USER

_audit.AUDIT_CRYPTO_PARAM_CHANGE_USER_swigconstant(_audit)
AUDIT_CRYPTO_PARAM_CHANGE_USER = _audit.AUDIT_CRYPTO_PARAM_CHANGE_USER

_audit.AUDIT_CRYPTO_LOGIN_swigconstant(_audit)
AUDIT_CRYPTO_LOGIN = _audit.AUDIT_CRYPTO_LOGIN

_audit.AUDIT_CRYPTO_LOGOUT_swigconstant(_audit)
AUDIT_CRYPTO_LOGOUT = _audit.AUDIT_CRYPTO_LOGOUT

_audit.AUDIT_CRYPTO_KEY_USER_swigconstant(_audit)
AUDIT_CRYPTO_KEY_USER = _audit.AUDIT_CRYPTO_KEY_USER

_audit.AUDIT_CRYPTO_FAILURE_USER_swigconstant(_audit)
AUDIT_CRYPTO_FAILURE_USER = _audit.AUDIT_CRYPTO_FAILURE_USER

_audit.AUDIT_CRYPTO_REPLAY_USER_swigconstant(_audit)
AUDIT_CRYPTO_REPLAY_USER = _audit.AUDIT_CRYPTO_REPLAY_USER

_audit.AUDIT_CRYPTO_SESSION_swigconstant(_audit)
AUDIT_CRYPTO_SESSION = _audit.AUDIT_CRYPTO_SESSION

_audit.AUDIT_CRYPTO_IKE_SA_swigconstant(_audit)
AUDIT_CRYPTO_IKE_SA = _audit.AUDIT_CRYPTO_IKE_SA

_audit.AUDIT_CRYPTO_IPSEC_SA_swigconstant(_audit)
AUDIT_CRYPTO_IPSEC_SA = _audit.AUDIT_CRYPTO_IPSEC_SA

_audit.AUDIT_LAST_CRYPTO_MSG_swigconstant(_audit)
AUDIT_LAST_CRYPTO_MSG = _audit.AUDIT_LAST_CRYPTO_MSG

_audit.AUDIT_FIRST_VIRT_MSG_swigconstant(_audit)
AUDIT_FIRST_VIRT_MSG = _audit.AUDIT_FIRST_VIRT_MSG

_audit.AUDIT_VIRT_CONTROL_swigconstant(_audit)
AUDIT_VIRT_CONTROL = _audit.AUDIT_VIRT_CONTROL

_audit.AUDIT_VIRT_RESOURCE_swigconstant(_audit)
AUDIT_VIRT_RESOURCE = _audit.AUDIT_VIRT_RESOURCE

_audit.AUDIT_VIRT_MACHINE_ID_swigconstant(_audit)
AUDIT_VIRT_MACHINE_ID = _audit.AUDIT_VIRT_MACHINE_ID

_audit.AUDIT_LAST_VIRT_MSG_swigconstant(_audit)
AUDIT_LAST_VIRT_MSG = _audit.AUDIT_LAST_VIRT_MSG

_audit.AUDIT_KEY_SEPARATOR_swigconstant(_audit)
AUDIT_KEY_SEPARATOR = _audit.AUDIT_KEY_SEPARATOR

_audit.AUDIT_FILTER_EXCLUDE_swigconstant(_audit)
AUDIT_FILTER_EXCLUDE = _audit.AUDIT_FILTER_EXCLUDE

_audit.AUDIT_FILTER_MASK_swigconstant(_audit)
AUDIT_FILTER_MASK = _audit.AUDIT_FILTER_MASK

_audit.AUDIT_FILTER_UNSET_swigconstant(_audit)
AUDIT_FILTER_UNSET = _audit.AUDIT_FILTER_UNSET

_audit.EM_ARM_swigconstant(_audit)
EM_ARM = _audit.EM_ARM

_audit.EM_AARCH64_swigconstant(_audit)
EM_AARCH64 = _audit.EM_AARCH64
class audit_sig_info(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_sig_info, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_sig_info, name)
    __repr__ = _swig_repr
    __swig_setmethods__["uid"] = _audit.audit_sig_info_uid_set
    __swig_getmethods__["uid"] = _audit.audit_sig_info_uid_get
    if _newclass:
        uid = _swig_property(_audit.audit_sig_info_uid_get, _audit.audit_sig_info_uid_set)
    __swig_setmethods__["pid"] = _audit.audit_sig_info_pid_set
    __swig_getmethods__["pid"] = _audit.audit_sig_info_pid_get
    if _newclass:
        pid = _swig_property(_audit.audit_sig_info_pid_get, _audit.audit_sig_info_pid_set)
    __swig_setmethods__["ctx"] = _audit.audit_sig_info_ctx_set
    __swig_getmethods__["ctx"] = _audit.audit_sig_info_ctx_get
    if _newclass:
        ctx = _swig_property(_audit.audit_sig_info_ctx_get, _audit.audit_sig_info_ctx_set)

    def __init__(self):
        this = _audit.new_audit_sig_info()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_sig_info
    __del__ = lambda self: None
audit_sig_info_swigregister = _audit.audit_sig_info_swigregister
audit_sig_info_swigregister(audit_sig_info)


_audit.MAX_AUDIT_MESSAGE_LENGTH_swigconstant(_audit)
MAX_AUDIT_MESSAGE_LENGTH = _audit.MAX_AUDIT_MESSAGE_LENGTH
class audit_message(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_message, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_message, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nlh"] = _audit.audit_message_nlh_set
    __swig_getmethods__["nlh"] = _audit.audit_message_nlh_get
    if _newclass:
        nlh = _swig_property(_audit.audit_message_nlh_get, _audit.audit_message_nlh_set)
    __swig_setmethods__["data"] = _audit.audit_message_data_set
    __swig_getmethods__["data"] = _audit.audit_message_data_get
    if _newclass:
        data = _swig_property(_audit.audit_message_data_get, _audit.audit_message_data_set)

    def __init__(self):
        this = _audit.new_audit_message()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_message
    __del__ = lambda self: None
audit_message_swigregister = _audit.audit_message_swigregister
audit_message_swigregister(audit_message)

class audit_reply(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_reply, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_reply, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _audit.audit_reply_type_set
    __swig_getmethods__["type"] = _audit.audit_reply_type_get
    if _newclass:
        type = _swig_property(_audit.audit_reply_type_get, _audit.audit_reply_type_set)
    __swig_setmethods__["len"] = _audit.audit_reply_len_set
    __swig_getmethods__["len"] = _audit.audit_reply_len_get
    if _newclass:
        len = _swig_property(_audit.audit_reply_len_get, _audit.audit_reply_len_set)
    __swig_setmethods__["nlh"] = _audit.audit_reply_nlh_set
    __swig_getmethods__["nlh"] = _audit.audit_reply_nlh_get
    if _newclass:
        nlh = _swig_property(_audit.audit_reply_nlh_get, _audit.audit_reply_nlh_set)
    __swig_setmethods__["msg"] = _audit.audit_reply_msg_set
    __swig_getmethods__["msg"] = _audit.audit_reply_msg_get
    if _newclass:
        msg = _swig_property(_audit.audit_reply_msg_get, _audit.audit_reply_msg_set)
    __swig_setmethods__["status"] = _audit.audit_reply_status_set
    __swig_getmethods__["status"] = _audit.audit_reply_status_get
    if _newclass:
        status = _swig_property(_audit.audit_reply_status_get, _audit.audit_reply_status_set)
    __swig_setmethods__["ruledata"] = _audit.audit_reply_ruledata_set
    __swig_getmethods__["ruledata"] = _audit.audit_reply_ruledata_get
    if _newclass:
        ruledata = _swig_property(_audit.audit_reply_ruledata_get, _audit.audit_reply_ruledata_set)
    __swig_setmethods__["login"] = _audit.audit_reply_login_set
    __swig_getmethods__["login"] = _audit.audit_reply_login_get
    if _newclass:
        login = _swig_property(_audit.audit_reply_login_get, _audit.audit_reply_login_set)
    __swig_setmethods__["message"] = _audit.audit_reply_message_set
    __swig_getmethods__["message"] = _audit.audit_reply_message_get
    if _newclass:
        message = _swig_property(_audit.audit_reply_message_get, _audit.audit_reply_message_set)
    __swig_setmethods__["error"] = _audit.audit_reply_error_set
    __swig_getmethods__["error"] = _audit.audit_reply_error_get
    if _newclass:
        error = _swig_property(_audit.audit_reply_error_get, _audit.audit_reply_error_set)
    __swig_setmethods__["signal_info"] = _audit.audit_reply_signal_info_set
    __swig_getmethods__["signal_info"] = _audit.audit_reply_signal_info_get
    if _newclass:
        signal_info = _swig_property(_audit.audit_reply_signal_info_get, _audit.audit_reply_signal_info_set)
    __swig_setmethods__["conf"] = _audit.audit_reply_conf_set
    __swig_getmethods__["conf"] = _audit.audit_reply_conf_get
    if _newclass:
        conf = _swig_property(_audit.audit_reply_conf_get, _audit.audit_reply_conf_set)

    def __init__(self):
        this = _audit.new_audit_reply()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_reply
    __del__ = lambda self: None
audit_reply_swigregister = _audit.audit_reply_swigregister
audit_reply_swigregister(audit_reply)

class audit_dispatcher_header(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, audit_dispatcher_header, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, audit_dispatcher_header, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ver"] = _audit.audit_dispatcher_header_ver_set
    __swig_getmethods__["ver"] = _audit.audit_dispatcher_header_ver_get
    if _newclass:
        ver = _swig_property(_audit.audit_dispatcher_header_ver_get, _audit.audit_dispatcher_header_ver_set)
    __swig_setmethods__["hlen"] = _audit.audit_dispatcher_header_hlen_set
    __swig_getmethods__["hlen"] = _audit.audit_dispatcher_header_hlen_get
    if _newclass:
        hlen = _swig_property(_audit.audit_dispatcher_header_hlen_get, _audit.audit_dispatcher_header_hlen_set)
    __swig_setmethods__["type"] = _audit.audit_dispatcher_header_type_set
    __swig_getmethods__["type"] = _audit.audit_dispatcher_header_type_get
    if _newclass:
        type = _swig_property(_audit.audit_dispatcher_header_type_get, _audit.audit_dispatcher_header_type_set)
    __swig_setmethods__["size"] = _audit.audit_dispatcher_header_size_set
    __swig_getmethods__["size"] = _audit.audit_dispatcher_header_size_get
    if _newclass:
        size = _swig_property(_audit.audit_dispatcher_header_size_get, _audit.audit_dispatcher_header_size_set)

    def __init__(self):
        this = _audit.new_audit_dispatcher_header()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _audit.delete_audit_dispatcher_header
    __del__ = lambda self: None
audit_dispatcher_header_swigregister = _audit.audit_dispatcher_header_swigregister
audit_dispatcher_header_swigregister(audit_dispatcher_header)


_audit.AUDISP_PROTOCOL_VER_swigconstant(_audit)
AUDISP_PROTOCOL_VER = _audit.AUDISP_PROTOCOL_VER

_audit.MACH_X86_swigconstant(_audit)
MACH_X86 = _audit.MACH_X86

_audit.MACH_86_64_swigconstant(_audit)
MACH_86_64 = _audit.MACH_86_64

_audit.MACH_IA64_swigconstant(_audit)
MACH_IA64 = _audit.MACH_IA64

_audit.MACH_PPC64_swigconstant(_audit)
MACH_PPC64 = _audit.MACH_PPC64

_audit.MACH_PPC_swigconstant(_audit)
MACH_PPC = _audit.MACH_PPC

_audit.MACH_S390X_swigconstant(_audit)
MACH_S390X = _audit.MACH_S390X

_audit.MACH_S390_swigconstant(_audit)
MACH_S390 = _audit.MACH_S390

_audit.MACH_ALPHA_swigconstant(_audit)
MACH_ALPHA = _audit.MACH_ALPHA

_audit.MACH_ARM_swigconstant(_audit)
MACH_ARM = _audit.MACH_ARM

_audit.MACH_AARCH64_swigconstant(_audit)
MACH_AARCH64 = _audit.MACH_AARCH64

_audit.MACH_PPC64LE_swigconstant(_audit)
MACH_PPC64LE = _audit.MACH_PPC64LE

_audit.FAIL_IGNORE_swigconstant(_audit)
FAIL_IGNORE = _audit.FAIL_IGNORE

_audit.FAIL_LOG_swigconstant(_audit)
FAIL_LOG = _audit.FAIL_LOG

_audit.FAIL_TERMINATE_swigconstant(_audit)
FAIL_TERMINATE = _audit.FAIL_TERMINATE

_audit.MSG_STDERR_swigconstant(_audit)
MSG_STDERR = _audit.MSG_STDERR

_audit.MSG_SYSLOG_swigconstant(_audit)
MSG_SYSLOG = _audit.MSG_SYSLOG

_audit.MSG_QUIET_swigconstant(_audit)
MSG_QUIET = _audit.MSG_QUIET

_audit.DBG_NO_swigconstant(_audit)
DBG_NO = _audit.DBG_NO

_audit.DBG_YES_swigconstant(_audit)
DBG_YES = _audit.DBG_YES

def set_aumessage_mode(mode, debug):
    return _audit.set_aumessage_mode(mode, debug)
set_aumessage_mode = _audit.set_aumessage_mode

_audit.GET_REPLY_BLOCKING_swigconstant(_audit)
GET_REPLY_BLOCKING = _audit.GET_REPLY_BLOCKING

_audit.GET_REPLY_NONBLOCKING_swigconstant(_audit)
GET_REPLY_NONBLOCKING = _audit.GET_REPLY_NONBLOCKING

def audit_open():
    return _audit.audit_open()
audit_open = _audit.audit_open

def audit_close(fd):
    return _audit.audit_close(fd)
audit_close = _audit.audit_close

def audit_get_reply(fd, rep, block, peek):
    return _audit.audit_get_reply(fd, rep, block, peek)
audit_get_reply = _audit.audit_get_reply

def audit_getloginuid():
    return _audit.audit_getloginuid()
audit_getloginuid = _audit.audit_getloginuid

def audit_setloginuid(uid):
    return _audit.audit_setloginuid(uid)
audit_setloginuid = _audit.audit_setloginuid

def audit_detect_machine():
    return _audit.audit_detect_machine()
audit_detect_machine = _audit.audit_detect_machine

def audit_determine_machine(arch):
    return _audit.audit_determine_machine(arch)
audit_determine_machine = _audit.audit_determine_machine

def audit_name_to_field(field):
    return _audit.audit_name_to_field(field)
audit_name_to_field = _audit.audit_name_to_field

def audit_field_to_name(field):
    return _audit.audit_field_to_name(field)
audit_field_to_name = _audit.audit_field_to_name

def audit_name_to_syscall(sc, machine):
    return _audit.audit_name_to_syscall(sc, machine)
audit_name_to_syscall = _audit.audit_name_to_syscall

def audit_syscall_to_name(sc, machine):
    return _audit.audit_syscall_to_name(sc, machine)
audit_syscall_to_name = _audit.audit_syscall_to_name

def audit_name_to_flag(flag):
    return _audit.audit_name_to_flag(flag)
audit_name_to_flag = _audit.audit_name_to_flag

def audit_flag_to_name(flag):
    return _audit.audit_flag_to_name(flag)
audit_flag_to_name = _audit.audit_flag_to_name

def audit_name_to_action(action):
    return _audit.audit_name_to_action(action)
audit_name_to_action = _audit.audit_name_to_action

def audit_action_to_name(action):
    return _audit.audit_action_to_name(action)
audit_action_to_name = _audit.audit_action_to_name

def audit_name_to_msg_type(msg_type):
    return _audit.audit_name_to_msg_type(msg_type)
audit_name_to_msg_type = _audit.audit_name_to_msg_type

def audit_msg_type_to_name(msg_type):
    return _audit.audit_msg_type_to_name(msg_type)
audit_msg_type_to_name = _audit.audit_msg_type_to_name

def audit_name_to_machine(machine):
    return _audit.audit_name_to_machine(machine)
audit_name_to_machine = _audit.audit_name_to_machine

def audit_machine_to_name(machine):
    return _audit.audit_machine_to_name(machine)
audit_machine_to_name = _audit.audit_machine_to_name

def audit_machine_to_elf(machine):
    return _audit.audit_machine_to_elf(machine)
audit_machine_to_elf = _audit.audit_machine_to_elf

def audit_elf_to_machine(elf):
    return _audit.audit_elf_to_machine(elf)
audit_elf_to_machine = _audit.audit_elf_to_machine

def audit_operator_to_symbol(op):
    return _audit.audit_operator_to_symbol(op)
audit_operator_to_symbol = _audit.audit_operator_to_symbol

def audit_name_to_errno(error):
    return _audit.audit_name_to_errno(error)
audit_name_to_errno = _audit.audit_name_to_errno

def audit_errno_to_name(error):
    return _audit.audit_errno_to_name(error)
audit_errno_to_name = _audit.audit_errno_to_name

def audit_name_to_ftype(name):
    return _audit.audit_name_to_ftype(name)
audit_name_to_ftype = _audit.audit_name_to_ftype

def audit_ftype_to_name(ftype):
    return _audit.audit_ftype_to_name(ftype)
audit_ftype_to_name = _audit.audit_ftype_to_name

def audit_number_to_errmsg(errnumber, opt):
    return _audit.audit_number_to_errmsg(errnumber, opt)
audit_number_to_errmsg = _audit.audit_number_to_errmsg

def audit_request_status(fd):
    return _audit.audit_request_status(fd)
audit_request_status = _audit.audit_request_status

def audit_is_enabled(fd):
    return _audit.audit_is_enabled(fd)
audit_is_enabled = _audit.audit_is_enabled

def get_auditfail_action(failmode):
    return _audit.get_auditfail_action(failmode)
get_auditfail_action = _audit.get_auditfail_action

def audit_request_features(fd):
    return _audit.audit_request_features(fd)
audit_request_features = _audit.audit_request_features

_audit.WAIT_NO_swigconstant(_audit)
WAIT_NO = _audit.WAIT_NO

_audit.WAIT_YES_swigconstant(_audit)
WAIT_YES = _audit.WAIT_YES

def audit_set_pid(fd, pid, wmode):
    return _audit.audit_set_pid(fd, pid, wmode)
audit_set_pid = _audit.audit_set_pid

def audit_set_enabled(fd, enabled):
    return _audit.audit_set_enabled(fd, enabled)
audit_set_enabled = _audit.audit_set_enabled

def audit_set_failure(fd, failure):
    return _audit.audit_set_failure(fd, failure)
audit_set_failure = _audit.audit_set_failure

def audit_set_rate_limit(fd, limit):
    return _audit.audit_set_rate_limit(fd, limit)
audit_set_rate_limit = _audit.audit_set_rate_limit

def audit_set_backlog_limit(fd, limit):
    return _audit.audit_set_backlog_limit(fd, limit)
audit_set_backlog_limit = _audit.audit_set_backlog_limit

def audit_set_backlog_wait_time(fd, bwt):
    return _audit.audit_set_backlog_wait_time(fd, bwt)
audit_set_backlog_wait_time = _audit.audit_set_backlog_wait_time

def audit_set_feature(fd, feature, value, lock):
    return _audit.audit_set_feature(fd, feature, value, lock)
audit_set_feature = _audit.audit_set_feature

def audit_set_loginuid_immutable(fd):
    return _audit.audit_set_loginuid_immutable(fd)
audit_set_loginuid_immutable = _audit.audit_set_loginuid_immutable

def audit_request_rules_list_data(fd):
    return _audit.audit_request_rules_list_data(fd)
audit_request_rules_list_data = _audit.audit_request_rules_list_data

def audit_request_signal_info(fd):
    return _audit.audit_request_signal_info(fd)
audit_request_signal_info = _audit.audit_request_signal_info

def audit_update_watch_perms(rule, perms):
    return _audit.audit_update_watch_perms(rule, perms)
audit_update_watch_perms = _audit.audit_update_watch_perms

def audit_add_watch(rulep, path):
    return _audit.audit_add_watch(rulep, path)
audit_add_watch = _audit.audit_add_watch

def audit_add_dir(rulep, path):
    return _audit.audit_add_dir(rulep, path)
audit_add_dir = _audit.audit_add_dir

def audit_add_watch_dir(type, rulep, path):
    return _audit.audit_add_watch_dir(type, rulep, path)
audit_add_watch_dir = _audit.audit_add_watch_dir

def audit_trim_subtrees(fd):
    return _audit.audit_trim_subtrees(fd)
audit_trim_subtrees = _audit.audit_trim_subtrees

def audit_make_equivalent(fd, mount_point, subtree):
    return _audit.audit_make_equivalent(fd, mount_point, subtree)
audit_make_equivalent = _audit.audit_make_equivalent

def audit_add_rule_data(fd, rule, flags, action):
    return _audit.audit_add_rule_data(fd, rule, flags, action)
audit_add_rule_data = _audit.audit_add_rule_data

def audit_delete_rule_data(fd, rule, flags, action):
    return _audit.audit_delete_rule_data(fd, rule, flags, action)
audit_delete_rule_data = _audit.audit_delete_rule_data

def audit_value_needs_encoding(str, len):
    return _audit.audit_value_needs_encoding(str, len)
audit_value_needs_encoding = _audit.audit_value_needs_encoding

def audit_encode_value(final, buf, size):
    return _audit.audit_encode_value(final, buf, size)
audit_encode_value = _audit.audit_encode_value

def audit_encode_nv_string(name, value, vlen):
    return _audit.audit_encode_nv_string(name, value, vlen)
audit_encode_nv_string = _audit.audit_encode_nv_string

def audit_log_user_message(audit_fd, type, message, hostname, addr, tty, result):
    return _audit.audit_log_user_message(audit_fd, type, message, hostname, addr, tty, result)
audit_log_user_message = _audit.audit_log_user_message

def audit_log_user_comm_message(audit_fd, type, message, comm, hostname, addr, tty, result):
    return _audit.audit_log_user_comm_message(audit_fd, type, message, comm, hostname, addr, tty, result)
audit_log_user_comm_message = _audit.audit_log_user_comm_message

def audit_log_acct_message(audit_fd, type, pgname, op, name, id, host, addr, tty, result):
    return _audit.audit_log_acct_message(audit_fd, type, pgname, op, name, id, host, addr, tty, result)
audit_log_acct_message = _audit.audit_log_acct_message

def audit_log_user_avc_message(audit_fd, type, message, hostname, addr, tty, uid):
    return _audit.audit_log_user_avc_message(audit_fd, type, message, hostname, addr, tty, uid)
audit_log_user_avc_message = _audit.audit_log_user_avc_message

def audit_log_semanage_message(audit_fd, type, pgname, op, name, id, new_seuser, new_role, new_range, old_seuser, old_role, old_range, host, addr, tty, result):
    return _audit.audit_log_semanage_message(audit_fd, type, pgname, op, name, id, new_seuser, new_role, new_range, old_seuser, old_role, old_range, host, addr, tty, result)
audit_log_semanage_message = _audit.audit_log_semanage_message

def audit_log_user_command(audit_fd, type, command, tty, result):
    return _audit.audit_log_user_command(audit_fd, type, command, tty, result)
audit_log_user_command = _audit.audit_log_user_command

def audit_rule_syscall_data(rule, scall):
    return _audit.audit_rule_syscall_data(rule, scall)
audit_rule_syscall_data = _audit.audit_rule_syscall_data

def audit_rule_syscallbyname_data(rule, scall):
    return _audit.audit_rule_syscallbyname_data(rule, scall)
audit_rule_syscallbyname_data = _audit.audit_rule_syscallbyname_data

def audit_rule_fieldpair_data(rulep, pair, flags):
    return _audit.audit_rule_fieldpair_data(rulep, pair, flags)
audit_rule_fieldpair_data = _audit.audit_rule_fieldpair_data

def audit_rule_interfield_comp_data(rulep, pair, flags):
    return _audit.audit_rule_interfield_comp_data(rulep, pair, flags)
audit_rule_interfield_comp_data = _audit.audit_rule_interfield_comp_data

def audit_rule_free_data(rule):
    return _audit.audit_rule_free_data(rule)
audit_rule_free_data = _audit.audit_rule_free_data
# This file is compatible with both classic and new-style classes.


