#! /bin/sh
#
# "$Id: cups-config.in 9154 2010-06-16 00:49:01Z mike $"
# 
#   CUPS configuration utility.
#
#   Copyright 2007-2010 by Apple Inc.
#   Copyright 2001-2006 by Easy Software Products, all rights reserved.
#
#   These coded instructions, statements, and computer programs are the
#   property of Apple Inc. and are protected by Federal copyright
#   law.  Distribution and use rights are outlined in the file "LICENSE.txt"
#   which should have been included with this file.  If this file is
#   file is missing or damaged, see the license at "http://www.cups.org/".
#

VERSION="1.4.4"
APIVERSION="1.4"
BUILD="cups-1.4.4"

prefix=/nfsroot/hico7723/rootfs
exec_prefix=/nfsroot/hico7723/rootfs
bindir=/nfsroot/hico7723/rootfs/bin
includedir=${prefix}/include
libdir=/nfsroot/hico7723/rootfs/lib64
imagelibdir=/nfsroot/hico7723/rootfs/lib64
datarootdir=/nfsroot/hico7723/rootfs/share
datadir=/nfsroot/hico7723/rootfs/share
sysconfdir=/nfsroot/hico7723/rootfs/etc
cups_datadir=/nfsroot/hico7723/rootfs/share/cups
cups_serverbin=/nfsroot/hico7723/rootfs/lib/cups
cups_serverroot=/nfsroot/hico7723/rootfs/etc/cups
INSTALLSTATIC=

# flags for C++ compiler:
CFLAGS=""
LDFLAGS="-Wl,-rpath,/nfsroot/hico7723/rootfs/lib64"
LIBS="   -lpthread -lm -lcrypt "
IMGLIBS="  "

# Check for local invocation...
selfdir=`dirname $0`

if test -f "$selfdir/cups/cups.h"; then
    CFLAGS="-I$selfdir"
    LDFLAGS="-L$selfdir/cups -L$selfdir/filter $LDFLAGS"
    libdir="$selfdir/cups"
    imagelibdir="$selfdir/filter"
    if test ! -f "$selfdir/cups/raster.h"; then
        ln -s ../filter/raster.h "$selfdir/cups"
    fi
else
    if test $includedir != /usr/include; then
	CFLAGS="$CFLAGS -I$includedir"
    fi

    if test $libdir != /usr/lib -a $libdir != /usr/lib32 -a $libdir != /usr/lib64; then
	LDFLAGS="$LDFLAGS -L$libdir"
    fi
fi


usage ()
{
    echo "Usage: cups-config --api-version"
    echo "       cups-config --build"
    echo "       cups-config --cflags"
    echo "       cups-config --datadir"
    echo "       cups-config --help"
    echo "       cups-config --ldflags"
    echo "       cups-config [--driver] [--image] [--static] --libs"
    echo "       cups-config --serverbin"
    echo "       cups-config --serverroot"
    echo "       cups-config --version"

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

# Parse command line options
static=no
image=no
driver=no

while test $# -gt 0; do
    case $1 in
	--api-version)
	    echo $APIVERSION
	    ;;
	--build)
	    echo $BUILD
	    ;;
	--cflags)
	    echo $CFLAGS
	    ;;
	--datadir)
	    echo $cups_datadir
	    ;;
	--driver)
	    driver=yes
	    ;;
	--help)
	    usage 0
	    ;;
	--image)
	    image=yes
	    ;;
	--ldflags)
	    echo $LDFLAGS
	    ;;
	--libs)
	    if test $static = no; then
	        libs="-lcups $LIBS";
 	        if test $image = yes; then
 	            libs="-lcupsimage $libs"
		fi
 	        if test $driver = yes; then
 	            libs="-lcupsdriver $libs"
		fi
	    else
	        libs="$libdir/libcups.a $LIBS";
 	        if test $image = yes; then
 	            libs="$libdir/libcupsimage.a $IMGLIBS $libs"
		fi
 	        if test $driver = yes; then
 	            libs="$libdir/libcupsdriver.a $libs"
		fi
	    fi
	    echo $libs
	    ;;
	--serverbin)
	    echo $cups_serverbin
	    ;;
	--serverroot)
	    echo $cups_serverroot
	    ;;
	--static)
	    if test -z "$INSTALLSTATIC"; then
	        echo "WARNING: Static libraries not installed!" >&2
	    else
	        static=yes
	    fi
	    ;;
	--version)
	    echo $VERSION
	    ;;
	*)
	    usage 1
	    ;;
    esac

    shift
done

#
# End of "$Id: cups-config.in 9154 2010-06-16 00:49:01Z mike $".
#
